apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
stringData:
    discord_critical_url: ENC[AES256_GCM,data:pViiKwOJJcu1YNEAvofuyYz23mBUdtn/qQWqJG2T4Tp36g9ebnGbMre4Rq4Z43bAlXQ+vh8DVcl4BatWfT3y3MqOqodH4T/TLwSbUmLQYqi4+4+HXqYDiLhowRjCvsHpPeSGFce+1DqlTaqg3n2j6uMNyeo0eBch0UhSAB2Q8Q==,iv:pvLLvihK6vyaUjtDqo6SXPTDVrdk1SoxDuNy+m2E0qE=,tag:HCIonWtdQ5ctKSy5gFtN7A==,type:str]
    discord_warning_url: ENC[AES256_GCM,data:cNQdcuB8stkWnBBKxzyTeftnWNnm9Koz7f1ndlT9AMz5Ro+4klw+A/aD+0fmL/ikZpJio6Ggbj0X1zUqrprIHV3XT1I4M8tsrNZ3FeukjlmMjBY31Nnh+RhanTVWRAq20OwDKVKl5bgFr3oYLScIqKYcPmr3htTaZAmRsy+QEQ==,iv:AxNCCe5DDEo/GDQIo4/xDJBlAl2/E11Ti3py/ZzFSEg=,tag:GAdKkd4Crf1dF/rUNDIFfA==,type:str]
    discord_oncall_role_id: ENC[AES256_GCM,data:HGW4wyK7MMWdSDCuGEG8lTPM3w==,iv:q9ULkydpLkzx5ctZ+NkdXBb+PmuZbbTtoirYN56F6gM=,tag:z70VTDfRrqKqS3/NROAaOg==,type:int]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VjBDTStIZGRsQ1F4NnpJ
            N1IwMUNiMkc5UUFOdDZLNlJ3a3Y2ei9VaW1ZCnAzWmlyMnZFY1h6S3lKazkzdytq
            WC9oODBzNS83akhVK3VHNTljODB2Z0EKLS0tIERicFFIa1AvMHFVUWl2dUswdHRF
            cklkQU0xeWZSZEFWeno2M1RjQjM5eXcK146sAvX+M+GoYviS0kdTlnc72mt8ZaP6
            Lf+ohKF5r7ZK/b0yzqBlv/lcMus7ysCb2YFYxc9mVaYUwc6VswilNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T13:30:30Z"
    mac: ENC[AES256_GCM,data:jzOcA9jWRqnkgcugKdv191deRMIq0VQ1lvvCYHyBMhaAm7sRTmqvhj/3WA/0ZphmvJroj4yt/1rce/zpCpiaQ9m66vkf73ShRoETE3pqnum7oKC+Eyo3axPCy9+nDIL89gLX9RRENZ3poAPnkgLD1m81bu6pS75Vfn+dZqdSAnM=,iv:o6wT8SRUcTHhFFBu/10SO5fnqQdSvaG1wti6wUDszLE=,tag:nT86z88tFJxz9/L8LWl+6A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
