apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
stringData:
    discord_critical_url: ENC[AES256_GCM,data:Ow9JDoWBGpF/jstEolaQYpRJ2D6+VXlesxWuWaY7OmmxPUW4iknJfOJGtWubrVMksLGEzsfPLVnpifDwCIG8hRigTSNWGSUY5kZIRz87TSitXf3FyJMUqaEd13I9hAIuD5nhzZtspiZCmseDZNUx+yktmkG5re4YCx5Q8hhoOA==,iv:r94zlPvuU1FiGEZY0iWSWVXKyp+fujkG0raDjDOGpQQ=,tag:IbFY03Q3koSwpKizduFxFg==,type:str]
    discord_warning_url: ENC[AES256_GCM,data:ZJO58FX22pz7cvy7nQINinapPtSQvbwoid/FalIPQcZ5wEuI3yrBHF2z6G7T7AF42j387FjGDu+6LE2mq4siWriIrcBf3m2eiq+PrKuRMAxpUVYiQDRWZZ1+2r5d9Qrarncb47qDzI92+m6iaBI7WUrSI7aR1bXL9AEjaJTJYg==,iv:3jwEIJr+1GJ6lGXTt5eVHObbq2wo/EasZlADDYyWhcY=,tag:WcFjqk45pWnuSadiQq9Ycg==,type:str]
    discord_oncall_role_id: ENC[AES256_GCM,data:E21grUjEZzfm7ODmQNeKNm2Szw==,iv:dwNpMLXMw+j+2BCPrWxVTCuDDY+w4d87iJzuObeMoo8=,tag:mal4zdMaCcdy6JOc/Hp7QA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2OUtpZkJUQTE5b2N1RWlh
            NkM4UTJiUVoyaTNObStUNWw5ZjU4dHhPekNRClNVakUyMm9xaExIY0s3WmI4cTQ2
            V1JHUXBYN2kvNUpva1dhVE1JQnBUbzAKLS0tIEhITHA1WUFhRWtBSEtFZ25PNmJL
            SitzQU1FeHFKUDZreldSQzQ4UG0xS0kKgSNvPqsC9sGL0nnyGoBRG4FS84aJcQot
            /r30pv4PiXKS6kHupqFCGfgdTYVI7bgJgdtsZbjB8Yun8hqGxRiZgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T13:35:52Z"
    mac: ENC[AES256_GCM,data:Ei/tViwRQ3t6p8hRaf1E6DDkCngRJx6nSozTH1hcOYDuPOIc0LtqnVRN6azFSDqV532AQisl4BdoLKi2hsShOb8wNCx+RPJaVKQ+gJ2I8CoEZC3gJDw0HnGt+iakI+OJDKkASHDdVAZ7Dg/kILd/73TBZsnIXXCnw8YTkZJE8Rc=,iv:ZA+NrmLgeYvrqq9dC2sms4YAwZBaXkHweuFWELa+A4g=,tag:2vwWY1P7+WCXOShpCzSWPQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
