apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord
    namespace: monitoring
stringData:
    discord_critical_url: ENC[AES256_GCM,data:5KG76DbHfEF8SLQkdohEtKXMmZjY80YLfon6aaUMxuxlQFwU7Kxo607Sctawlpv/t+vsH7KlDnjkJD6ZwuOK4/x4iCglpgYocBf1jK/W5muNSmG57Y5WIWcccZlnuWlsjsS8B9JEuOy6piQW0PmkgdpzTGYRMTVr5CDaQScOAw==,iv:3zfTXbRWNuiMAcvyaQM2ZiZNsUpVEeiCWV0UcxLDDag=,tag:O1DIUDkHGPc4x0GxB+bOmg==,type:str]
    discord_warning_url: ENC[AES256_GCM,data:+7tXBHS5qKPai0UEwzjSTSuf+CrHjG5K6Zn+6fB3FUYKVyvNAZkrVzxGNQ/HUErPGtT5RyvHxhPDWtRBWlCH39oC8TJblmQFgUXRYAlqd05xW5Q0bbNqXeMMOqncuvWJtM0VA6X0PpvCmkz2+SVgDbnngU0J6YvzLwHe/NtawQ==,iv:2nlxzKnQGx6+x6nyI6tg6d6XulPxh7/rMKdMLvySFhA=,tag:g+Zs8VuGmEMKIXPhMNvAaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxSHBUWTJiMEIyMHdRUy9F
            M3hQaWFYdXRXTloxNEdoR0pyT2lQTjhUYnhjCmRZeFpYVHJjN1JkMHA1UHdPUWc3
            UkdHTUUrdmdhN0tzbFpjQk16S2Z3ZEUKLS0tIG93MzYyQ1dTZ0VCcUtYQzB5NWpF
            bmM4KzlYTUtwejdFTkYwYjQ4a0tmWlkKIDahIib1i867nbcxEEoMyKQafwRNqCvt
            7nqe8YTDcPeojPdFAJx/i6aZOgEvF9lsJ9NmUUTSKJiZOu0bwudaiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T16:50:39Z"
    mac: ENC[AES256_GCM,data:QdFo1UvZiZWq4p8zyCkKzZfneFuSRACG5nBGcR9irHUPka3QV6Z3FXkmjbs7HUV4ZyxuemrcOUxjNit8EZ0DKBbbqidfDppRxDZhU8pY6jKo1PpTzb7g23fxtRX0hfSexKm+Yg2Lb1NfRh0RaA6FsMI8d0SH1xqVCDQYR/EI6xk=,iv:lQk1mFdlabp1rkRcTJ4Aplln0vsuO6dPYom5GoQm4bU=,tag:cVxC6+JSo4FwU7U/o/b4Nw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
