apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-oncall
    namespace: monitoring
type: Opaque
stringData:
    critical_url: ENC[AES256_GCM,data:AWlFpQxvPPBnDOxJqgvHMz6odZ9ymrbbTBU/V0x3zqZysb8+YBpEVGhowaezr4vLXpVUmzPhuA4fEagKBpaljGh/Ig8b1L7TYJ3q6ZHy,iv:s3fP/UiP4DXJDnKx412khx+Aa18xN+d1sxCv2Xq6dmA=,tag:/7CRpH5YgbJWaXc2/Wpt7g==,type:str]
    warning_url: ENC[AES256_GCM,data:mN/H8QdR+Rbzmg2tm7YOcGDSWVgZQNHvUps+XRFq6iKET1dhKE64wS6O7z+XA7D2uhAgNIw9EnzSGYpPN0OIAiAbTdZX4oV+omEeIUE1,iv:Z8jCC1352rzz5AdORcrXvDQYO3AoYVnXm6g/bNHo8Pc=,tag:YLfnagIo2YYpZynFMRRBaQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEQWF1cGVrVzhyakVZMytr
            dk9zcFBxVC9TNVA1MVhqamFteW02dXlRQXpzCkd3T0VmQmI5T2ZGazBwbkI2Zy9m
            bXF4aUFRb3Mva0F1MGFkZldEOUdEVDgKLS0tIG9rS3pkbWluRVpRNkloVlo4b3R5
            RUpwUVRZaHM0K01yMHprWThub1g5MEEK/DfK4TQO74f7FxjX9UGnZ3FEQrgtD0kf
            Bre6H4N09c9MhrKvcm4k2/wxblSM2XfB65MLEOPvOa/9eeNwmOEmdw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T21:22:42Z"
    mac: ENC[AES256_GCM,data:ubIH9CJ+CE9fufxTa+a1DDyO405GAJhLE5XNCDP3IgYGlxYIdbHpp8ZJXPYasQNa1Kz1uqlGOxg398UI6K4poD8JIMK12T24kCihuS2DB+7SIhA3QN4HiUkVhxzekyGVqlhjrlBi54oo4a28n+WQddGBjR9Au7+EskQMp2+Lt60=,iv:hkOi3QuW46IenztOHMrZ8+IHcg0aWVEk0KcI8yi3tNg=,tag:1IWVOsN8lwI83ZPV5jsOYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
