apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-discord-proxy
    namespace: monitoring-oncall
stringData:
    discord_critical_url: ENC[AES256_GCM,data:ebAQCUSVWJrPKCQ/w8Fin/FqwfeDjRHwhFjcy9JY/LtG5QbRr6NPUI2L6ovwniS5U2qitODvv2EihoZkmtr1BVp7FRrfA+q6Czu2sNfOiHn12L8oTd/6Z08m14EU7S7GbbBZzyOcq+FQzBvhRTy7ViewpQc70mYBOQ==,iv:C1eb2JUvYVGwpN3oPUBQUHWCQlHrqd9pBXw05HNlBx4=,tag:FrT1knS0nH5/8pX12qx1OQ==,type:str]
    discord_warning_url: ENC[AES256_GCM,data:zY1zde8Etw5VHJlTxDHxJOggRyVIeBDQ4wQUqHGqm+mWgn0HrghA6j5R36PHjQSCQfmcZ56CFSCyV3qjrCLm+ZjhZFfiLPyV7rH2DK2koJQ1C15sTfFj/WBI47P7CsNvvbAuDWlLOJZgPcTifVipKEAChiHYF72R1w==,iv:mu0cpnFzUq8tnXQJU7o/eGyGMSkzuf9hBptPr9qpjgw=,tag:qqvVOkR2pRnerHhYWdX/oA==,type:str]
    discord_oncall_role_id: ENC[AES256_GCM,data:JLr408e7BC68fiyvXEJsEvF5EQ==,iv:uSMAncGO81xNHRVp1Wo6RCie7he/m+Po7n8Baw+bcQg=,tag:EqUeOf7JdBPItvVhupkS5Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Z3g5QWNUZWJYMGtQREVt
            bXF1d3RDbDA5bnBqZWZkRGczU2JDeWwxTlQ0Cks3L20wNkJ1ZWZTbUtOZDBTNi9I
            blMvWUUwd0Q3SnQvbFB5cFlKQm4rdGcKLS0tIGF2cDQ2WEUxeGE3THhnOUhFRnEr
            d2RkQWhwdTBhUWI3b3pBdWg1RkNnOW8KGJngAhZJ9nX/tO/xzxHtCO3KWi1Pz8Fp
            OMo6D9mCao+Yy5JnBZFCStjy2kkC8eHWBHbfRxQV3WQAW+JJjoFSqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T13:58:55Z"
    mac: ENC[AES256_GCM,data:QQ/QVQ7TpPs7cTj37JuIvE6Yp7eQXhi+nSUPetdPcIUg5M9vr/ZiINuw4+OWOr95sFx0q/LjB0ySncckljL0RDPi+ZhY5Udv6TPww12AEKEeooearLTI+Zcf88JECtRCX58MzJpLiTyHdeCq9iyvHFF4foY8MOjnpIL6YuDq+mQ=,iv:OoNlmbR/p2wd3gUVxNvMKksWoeFbK9Y6lCKeu8NbT7s=,tag:BjLtfZtmA5M1AcSjl4b8rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
