apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kimai-db-credentials.yaml
  - kimai-admin-credentials.yaml
  - monitoring-grafana.yaml
  - notification-smtp.yaml
  - notification-smtp-monitoring.yaml
  - alertmanager-discord.yaml
