apiVersion: v1
kind: Secret
metadata:
    name: notification-smtp
    namespace: apps-tools
type: Opaque
stringData:
    MAILER_DSN: ENC[AES256_GCM,data:WZtxIzc0kf7AccAHmXnkF+xBLB/zWIrxsQkGbCfHdwL/SCg5iPRdYvGhSfNTomkq10UTZd1oSkbFms/5lm7FJT1cAfARCXdo2ybe+y2b26T+4Cyl6FADD3EglQg=,iv:C1novIgShSYQppYbNm92Ok41LeAIvmhF6yXFdbMMt/Y=,tag:CZGJYzU5jPvyDWCSLlKXSg==,type:str]
    MAILER_FROM: ENC[AES256_GCM,data:SgZPE5fG2dFEKY9EGK8WFgteRG3I,iv:tPXP8QmMJOs3BQ4oNmTf5Um9EwEziEQonDizaCaQmao=,tag:umP85s/Z4OgUPOIFfZvZJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRk51d053NXJtYktCS2Ey
            cTdOL1JMYjdHbWdDV0FhNzFkYlpjZEVGalNvCndTS2wvamVrKzhlc2RCcitHRmRN
            NEpGRy9EQjFKMDVUN3k1TER3eC83MWsKLS0tIFR6UTN4aHFXcUJQVWhDeEx0V2JB
            NGM5MFFZWTlhSTRaNkhNdDJTdTJEeEEK1gDqJymPcEI9oXDA0fejX6UmsdqhlMNe
            ns2twrW8ttYaPd18SJ3yDYIVlhCrAHsL3oQPSDfNDLmBel1KTbpWrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-11T15:33:23Z"
    mac: ENC[AES256_GCM,data:9jAVc1YlT0gq0Tc46RnLDCEPzyt2Tp4LNNcPSxYUzWVFi3SRoXwA3e/iTwnJJo6OdOnl4bYIoW4r+GQOqTUEOh3Zb9pbNI53rp2oaeZ80oTfEnCW5bklvoTATsDpdYN3Cxwjkf/KmxQ0xGZPzgFpE9wy+YOhtaR4VzKXOkTejLI=,iv:fM/7++tsWwdgB+Uq1SQ3vOSdoFibr0dR1CgJ8ok7IbQ=,tag:O2C1WmtNXhBSuxsI3hG8rg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
