apiVersion: ENC[AES256_GCM,data:JXQ=,iv:oxYKWG2wsmksR8tffLX52cdJaEmEV9cKgSnE2xXw3Bs=,tag:BNGW7ShCLMYzsLNTdi3odw==,type:str]
kind: ENC[AES256_GCM,data:5HO9xO/G,iv:8glwDnzfx3HATghRtit2k01x+yo+d9xElhgTJ9x/d7M=,tag:3jX05z8S2/7XhtpwjOQeUg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:T0LxqCpuc/Svk7ghiKk=,iv:hQz/6TcKDfN78zyK8b4Cx97iSLD3INbIS477NT8isO4=,tag:xidKCglJRvIj6IvTinqYkQ==,type:str]
    namespace: ENC[AES256_GCM,data:NOKEuEDa9f6LWJoWz+c01cQ=,iv:Sz48pSEYmHztrABU3JFuR2m54lPNg4WlxYi8u6A3zxo=,tag:dqXyGB0R0vFMEoAo5DBlOA==,type:str]
type: ENC[AES256_GCM,data:pzqv040S,iv:ngF9NtDCIxx4tD3sXTUZfAK4A1+RY23Ux1MS9XMMCrU=,tag:DaKI+jWLkdTxU1hGzXRAww==,type:str]
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:spskFlRYy5DjP3vfkWD4P+eJQp3x7BXxlg7TBnhc9B8=,iv:c02SUUf3S1aafLizkhB68to2Z41DNTIqaWxzOi7SbDo=,tag:n1xhA0E1BNRqmGWuRCIFug==,type:str]
    MIRAGE_SECRET_KEY: ENC[AES256_GCM,data:5nxTrhBE4YSSK81zn5eDgS239M7CnfG+XmRq/4D+7tU=,iv:EUfVZ/XZ0rhLkKR+24YfGgmVz87g4clXopN1tQ2r16E=,tag:vm1CddPpyjV1GgTADQMAuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIcnZ2MWxscEdRUG5FSWxV
            MDZFcU83RjRac3BlL1h5S2U0VUd1VjZXZ0N3ClRCcjlBMGFWd1hZajI0ZmQyeTND
            Y0JCM2kxb1RMcTJOdTBtZ0o3TXNtNTgKLS0tIGN6UlJKMUdNS1ZCbXF5NW1kQkkz
            WHNNMkhodlJQTnVXS1hzSVR0WFljck0K42pgDzvXDqBfW4lZRL4liTH3EJD8fDac
            /Tzy/egtfNMWY38NbWsZdwPCBuPcw2wVJVTbfVP2ZF1GXiTW/sVNiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T23:52:14Z"
    mac: ENC[AES256_GCM,data:UVaInaR/oWZW8oWqjWqLVtSmxmceS1p31kwoarb60Rew1t02lO3koTEkZGfLMqd/L7H1AVOXO9ARw8sZRBWLfffGsw9d9vLsv3uhCZrPo1ECLlgrnR6kUpKrU/cbD3n4ufJ07ZkICYKlSY9YyDjseZfma9l47eYPsL4+6g76lzY=,iv:7O9kQw8VTkLN+cSwYjsdkL+tr90tAdmLZLUSRML77dY=,tag:k21KpGDJBS55UzwOEVnQow==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
