apiVersion: v1
kind: Secret
metadata:
    name: oncall-secrets
    namespace: monitoring-oncall
type: Opaque
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:/CFjPeyqFDn5ZYLHGo3sAj59xnqJLAR2uNEDG4PJMogRd0w/OluXEUg6QurVVx/C+cER8IRFFytJl7/x7qOAyw==,iv:x9VCdsbqNCStDqO6YfH+lr+zkFbwd1aSqt89P4Wauaw=,tag:ce9irA1fw3tztoyvqULd/g==,type:str]
    MIRAGE_SECRET_KEY: ENC[AES256_GCM,data:AsHm1QaAhTLsziQ6ngOPpIOMXR0x8CF5Ob2W5baY4runGPFDqdcFHQnaZQZw1M1rQimOgh8ylMQSqyTZNKwmFA==,iv:Mf2e8j2qG3y7QUoPoS/b4axSTXgzN295F7QDWKlqToA=,tag:GKdc9bOrEQlkZb/ebHPlWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1ekhhMXFRbTlwTlN6Y2RU
            Q013ZDBVYysxRndnWmZHYS95QTFWS2ZHbG5RClo1VDFZRnJxaWZVMnFOR3RhY2pJ
            c0xUTm5PZ0cwVVd1c0J3UDJzck9jalUKLS0tIGpXTDVvcWE5OTNxanF6WmJtNkxq
            TU4vdDA5ZUtoak94RjhBemEvZWJuV0UK6RMFr6jsxaqbIJQMYJh8IXeGTkK3f6ZD
            iaaa1P3bLF/nqK18/hgjdX1HkSG3rCa/n8Fq2xlOMrFx2sGIC4+edQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T21:21:17Z"
    mac: ENC[AES256_GCM,data:nMndkBEhMSzKy3hGGhoF9M/5U0Cgx4uIthxw2JOBthlupzplE/3rRb+veizuFYOvPNMq9CTwDp5R1LdIQhSWGQo7zyee2inpih13T/SRztO1TjuUpFHJ2dk4PrPmlda3q4UDx6eHbYar+NUw/4xTioGW+GeYVvjVrXJ+Ha3kuBo=,iv:XzVAkDwHaw+lvaEprc+mzUVO7V6TySvrXaQGorvKtio=,tag:t8y6HrUxiEddl7w6WDjH3g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
