apiVersion: v1
kind: Secret
metadata:
    name: oncall-rabbitmq
    namespace: monitoring-oncall
type: Opaque
stringData:
    rabbitmq-password: ENC[AES256_GCM,data:wLgIorF5luGkQ5WEtTDMc/vu9gvsD702zGVyb+j5cSY=,iv:4GNHZiRJHJf5XZuFfXaLSVO8yflkD8MhVF1g1jEeQZM=,tag:2nJNsq7XamEOjzilbTeqHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjK09aTVRhN2J1YSt4UmRB
            MmErbTAxOVlPY29rRTU4TnpuNll3ZjNLaTJ3CkVRNWM1empMdkhxMFJlNTNvUGI1
            bGdsanBDZFQrRHJtKzBRZDJrMHd2NEEKLS0tIGxBWnpsSkhjdWoxUUtjNWxVODBh
            dzVJSGUvVHgyeUcyQ0dTeG9WYjBtODQKml8P0oam8XVQjiYouUkfmLH8NT0rs4Om
            T+xn4Gt37ho8XXetL2yYQJVBE6QJeW0+V3zU8XrNTuQJRMTVGsep6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T21:21:53Z"
    mac: ENC[AES256_GCM,data:oUowe7NW60OPTRBojEJjeZV/DxJB3yLjsPf2MO6KRP1m8G8lcYfUWS9TvlAKbYy+e85mprIHdgqQG5Ypo10m7xBtgau4H31lw5E8onKurtVlaVteEPvttX3lgoGUf2u3VOJ+vSPzJXxjBnT7DHxHbtY1etXSlAGeGsUtnrONthU=,iv:Sx123l0D81LpJTp9l1JyFrZomXov1Fc8BmGl6AIrHHQ=,tag:txjG7ZvzhCP17n09JRKOuA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
