apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rocket
resources:
  - ../../../../k8s/vars/secrets/notification-smtp.yaml
  - rocket-bootstrap.yaml
  - rocket-mail-url.yaml
  - rocket-mongodb-uri.yaml
  - rocket-mongodb-user-password.yaml
