apiVersion: v1
kind: Secret
metadata:
    name: rocket-mail-url
type: Opaque
stringData:
    mail-url: ENC[AES256_GCM,data:HB//BXf84Ym9qp/9g05JKh0GSMggnTN0I/UDOu5y1Z+qTWsAXmH1kzZTe6w++yu44VjnGKMA3RIgsixy0A==,iv:v7H+boV2aPj+v7kMpmazoHpogtYxYqw1IbspmVplJRE=,tag:K+wcVCV/XC1xSnvo/wJ8kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdy9sc2cvRk9PMytZUmVT
            QTJzSHdKeGY1cld5WGV2L3lUa2tiTlNCUURFCjdSM1BtWWpXVU44eEdHcElrSkYv
            Vi83eTFDSm9Jb1NuT1cxVHJmS1Y0NmsKLS0tIGYxbWo0UUZ0NlBnL1VxVXdkQ1Jz
            c2xibkc1NEhlM3FZa2xUWUtzSEhaQjQK77o+oSP3vCiJ5KHWNDXV9umXwGy0CTaw
            Ei9rOHVd2cuSs0KJgeVZ3dc3tPH4hbvdqoOFxTtUAVAlE6+aY4zlUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T12:24:18Z"
    mac: ENC[AES256_GCM,data:jCpXe171MDAVyo/EkjrKkIwPmqdZk4HsD1LHmmspvcCKRZt5xoq+QLfywqOOy/S2kfy9Fejytutf0wcNQhpUVGopgyly+qPWvT0jfGDiDOSt+iWNzxp3/PVB3qSqd6JXxmTtajHkqjZYWR4WstIMaa1cnpPbJEz3U0hXBqtMLO8=,iv:D9ZXjCah62KzuNs0P7T+iTYCoW6JMIXtPNVU95sjhAA=,tag:urEATg3A2zrDpII1f7rilg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
