apiVersion: v1
kind: Secret
metadata:
    name: rocket-mongodb-uri
type: Opaque
stringData:
    mongo-uri: ENC[AES256_GCM,data:HAT3ZcgbN1DADkS0vA8CyXv27cJkEuR/5dmHLu/ACTqEola+HcgeM2ctPhsJNZlxMbxU2nnQIoWp7z1Un8bljGfuS0X3NCPwaFZmRaNo7FKJRaA7kCNQ0vvhbpyE3rQUkAkgcXq22LQLP1hRw6NYm94JahVRRkGenVakaBMV0wFVX9xs2kHrGJDWZxCuFXgGMSKxo1Ka283DmUTLSkigIHWIiDT5mghkdhb38xQ09SzO4A==,iv:3HvG77GRx36jsb24FANZRLpzPithKxTO7bD4oNc/I5k=,tag:cTEcs9nZHieUYA/4GU92iA==,type:str]
    mongo-oplog-uri: ENC[AES256_GCM,data:ge9vB/BOLW8JmMQ+n1gYXDzo2NxW5ndkDTi6IwIjtLckmidLMifGbT4Nl3kPrrpREnXjdb24/1Fd0+WedTp1+RAiFvII72xH5oWIl/WiVZFLA6ZJVNUVn2+0icENQGVQU1G9xwTNcU2mBEBjnIXJqHtTDg0YByd1d7fFKEnGA6OkaBnB6RFS2pbugvubJZFcyp81L0EiT1m6AwwWfXahEwGPDmKmngzlVOwIpx4=,iv:IRExni/i1iOZ0mVzI4I3nWffTZ7FU1QgRgVCdhcCFoM=,tag:TYGUuFp97DrX/r46VE380g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByRGcremh5SDkwWSs1RktQ
            eVIxcmNiemFJRS93d2ZTU3EvTnNrTUw4d0VzCk1FdGFrYVJjdHZkTUc3c1pRbVl3
            NkJIUm9PYU5PSXJuOElRRTd3Wk1Tem8KLS0tIGhRdVVMbmhjOWlXSkl3MjlnKzZu
            eWpVK2s3SDFxcWg1SzJGcmdOTS9rTVkKj19hzdKQMf3FIFtVzteeOI7WfO2J2U0m
            SaFFsLeUyKLrJ2+cdDwMPZJK2m4APIC1MbLZC51Vm8+HB+2Ea9RhYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T12:24:18Z"
    mac: ENC[AES256_GCM,data:OuNv+eMgk487Swj709ZgcrYLDd4T9h0nN9tEHkIzC6z18j4K6SU/i/KzQHXMOygoKdRtfbw5nNhLxZARxBt8STpHInC9LaIuSab8uOvnVNq9wlG+3CgAeh0JkKbP6HJYwvKHpR7nafLS8EGGg9jRzmTDm6bkaxY+3SydYdIbNgc=,iv:QmsgHbtuvl49i/X3cQ3K2mNEHrDlkocgiICwzf0fvuk=,tag:C4vpCtDI6OQCKtj4RK40kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
