apiVersion: v1
kind: Secret
metadata:
    name: rocket-mongodb-user-password
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:S4YekPHRAJ4qkobNqerJk1cLcT6BWkdKALbJRbpeyG9nQ25v,iv:tsavRd0aE+llpfyNA49Y27RqVt4SpEmQJ+B7ZoSogtQ=,tag:IZL19GfFWL2cuqiMWhgO/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjN2lsT3lqejVhYW14VXJI
            OE5ldUdPMUJVSkI0Vkh6dmdvVlF2WXgxT3dzCkRhSmMzVldVK0oxWVlIL3RLYmFm
            Z2R4MG9EdEdhY0lvazB5cGpCOFF6TGcKLS0tIEE5YXJJWTZyKzlXcjhrbTVaWjBG
            NFoxUWJDNTJWS0pFRDlVMmtxVWJyNzAKV62AM9PrZoVIyE5sinPiJbUBM4bBTVAc
            6xwbpv8ovf9WK0h4v1loqJQ7f0HrUESh15jFRXXwW8c8bip6sV9pEw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T12:24:18Z"
    mac: ENC[AES256_GCM,data:uCirSLMGtPo0eyNeYAnKVYn28prHiPa6JSJkBYbjQxH0BK+OOtvcVsB2d6lA9S9CkLo6QBO1Oq9h78SAGAw8hYH+n7duGmLyzMYL3qXupiZ0bfT2bGaNrMU0WGFPWUprAhlEQhFxpOqJdIvDwQBwkqzHyijfiruTODBu4zrWMmY=,iv:mmcC8SJDOvnM3aSs2ZgK2DBK2/IjUO6VBRGKH4k1Brc=,tag:Y+vq5xXN/Lf/ha4Gc8lSfQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
