apiVersion: ENC[AES256_GCM,data:oQg=,iv:lcFzXqTY8Klu6AhYnkkIV7O5/nVUVtHYxWb+DPIVAhI=,tag:gr5dbZLP6XFq0ngmDOj/UQ==,type:str]
kind: ENC[AES256_GCM,data:JD56NaBE,iv:rGkZxfJxBvN1qCH0eg8rF2BcaL2XRB2e0kuuEeQHyPk=,tag:kStFIU5FkwvTH7e4TQ1QNA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:JJpcP3xyuijLUkEF/J9OGwYWdQ==,iv:Ka9NTXOG/K6hk7hQWB3YnwjTQe3llJIcOb/IwEaiBzo=,tag:nXtJSlan7rr+1pWHUR2GdA==,type:str]
    namespace: ENC[AES256_GCM,data:7VhvKUo2m0UNew==,iv:RJRp/G1uziNeY5MQo75WeelbiC6JUK0wf2v0pSM4e8w=,tag:TohoknWG9Y5UcIIM7X9qTw==,type:str]
type: ENC[AES256_GCM,data:16zGBBIh,iv:AZhdkjG2YHa4cBtGxkHPpfXrn47qlgA/ZtNKKxU0S3A=,tag:wkwh+GpT7aJFaLaomnwT+w==,type:str]
stringData:
    critical_url: ENC[AES256_GCM,data:nQIs6Txxp17HTmYChC41/V5mhKA0uc/VOjCRuIPWXoyMLY1Iz5WXEe286ElLJGFwyqMQyJ1vnc6GF/cxqrSKojr9FwEr+jsi9Pjp5ob8bQbG8O+9D+hjbvT5uCgBU18pBQhdxGjL,iv:ekeNWpSHrFXyU1qDYehduYIZW8P9GmS+zKuSoeDGync=,tag:HQdFzHthdIWZi9ewkIbZ8Q==,type:str]
    warning_url: ENC[AES256_GCM,data:MMS6bSs3siEeG1QFEOUZIclcpb/QzvZnp5PdR3fHh+9X9uZF/cXQFaLXkOV+GReT60H8JXNLiWcdLbYZmL1MB4OvaQ+8f5sUM4X8jh+hWxpkhoNuWRdW3+JyunBR1fQV/ET1CxkF,iv:i631+7Phlli6ZeX4jwp3E0dubBitIoXb6ZfHoesJriU=,tag:+VVCIHx8b8xLRkKi8Q0c6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpSmFoYVZVdWhCTjZLdHVs
            UEZpZWtRcmhVYlAxUzZDazZ1dC9OTVFodUJrCkU3c2R5VGNaVmplZE83c0VwMlJQ
            bEYrbFhyRitnK3FwcEJFSU9pbDU0dFkKLS0tIHVUbFVWTVVIbHREdWROTVJsb0lx
            Sk5UdGpIY21CNktqOGJOMUhDcTlVVlEKzYwGNCe0q+2G1wD7U4dAHAOkuk4e+KKx
            CTchpG2nCAdFanr8wPcDR4J3nBDbdI/y/re9Ii10+PY+tnZI7rv7fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-13T01:34:56Z"
    mac: ENC[AES256_GCM,data:s2or/zOcOdwTJbEjt7ruBXNaIEG0ccCVQNieOlZY7jDbDr/uigozXq4zO6/4lJ58W30Yo5uUdyhwuZ9V380iBtNCwj455CIyufmzD2mNevFocIdY95RTYXiLRIl1TEhJ1p8UhBFC8BSU6cd4kOTrc3i33YHLEWjCMoSlHN0RMso=,iv:uP5RcAGf/waafKCd7+DDQtv2Brp56gPeS53J9gB8+4I=,tag:3BmiBr0DCXQb9Ego+yHmDw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
