apiVersion: v1
kind: Secret
metadata:
    name: jenkins-prometheus-scrape
    namespace: monitoring
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:ajAi82NManhSfV3TKdo6BvZA,iv:OOnMOn2EvbrqTSnT4PLC3Lgzk5KJ0N7qvH0rs9oT7Rs=,tag:UFZLbqnCi/gvgT/pHBa0kA==,type:str]
    password: ENC[AES256_GCM,data:xmoxhlWqC9hcHlnc/e2ouHOMF8rB0LxlgOmTtUsOlPuvsx5f91tMxSmAE2KGfN8yaJ0jVCxBtd3NXV8GiGfDIg==,iv:eviBBA3Pp51thyj0ipSAYtJbsZnKQOFyDlJEbiV7Msg=,tag:7ork6Fx2g/RvKW6Zfpqm+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRTEpWYnF4bDhsQVlrM2ZB
            aEUrWnd1VlhjZitUNXNjNDFRclg5dXlvbUFFCk55eWJacDNTWm9pakU1Y2paVngw
            VEtUbkgzd0d2VmlKWjZuMlpLRTAyN1EKLS0tIGVCZlRiRVA2eUJuTEdZRnV4ZFgw
            c2VkMEFmczZqNVN4TjJhdDVkNkpPTUUKnbIGBUDrxNhiFJRDL0enkhvfv408IUva
            gzqw81reiZzdhZkflUyLDnfUIp3E2Z2Lf5Zxnnu16n1ppMmssa9Yjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T19:18:58Z"
    mac: ENC[AES256_GCM,data:zn7LErRMlyHl/T1Vzajz7v8iNkHBf68x4tpg11ERKaIQDlGsNgKLqaTROPajnXi5744yUnBGlQSTkI2r1B+MM2GATLbX5bzKUVCLLcBmny0AjScKZrPU9zGMzhDiSl0vnerJc6MjYvrIyWqpCiuCgEZjpbZ3+8EUClTbnXwyBck=,iv:Q3VLm6nf1m+xs6dc7S9bolp5Ciz3aU1lfDWels0SSJY=,tag:u6fsLKUIr1lDFZwAyAqApg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
