apiVersion: v1
kind: Secret
metadata:
    name: kimai-db-credentials
    namespace: apps-tools
type: Opaque
stringData:
    mysql-root-password: ENC[AES256_GCM,data:Vbo/UTUK0XHXZ0KeIpDYI0MlYF6Unpsj,iv:1NBvAofRyYwpk3MnW+zLVvWKp4gqf/AyRxSRSq75kyU=,tag:T4GTd9rSQ62vtv0e0oPWaw==,type:str]
    mysql-user-password: ENC[AES256_GCM,data:o3z+sMu/jAeenzcMCQ5rSkbKwDUgKfMK,iv:2ChpQVjZTho2LF95DRjuZ57sUlMMCc5bsvw8kXCkygg=,tag:AUUu/AICUq3gegfpwkVK5Q==,type:str]
    database-url: ENC[AES256_GCM,data:HxEqX2qoy7qc/+i4wj7Ud+hHRIRjsPulIKnwA6lRTpkDHfaDpnN1QAcGNWCpdcj0lib+5tWyNPLi84NMIJBt,iv:j9AFQf+kXH92+SGlXiN5DMyjCVNC9oxppeH/sbgju44=,tag:Q+y21Xay+VUKaijOV7JxXQ==,type:str]
sops:
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMXpPTlRLL3QyUlVmcyth
            WnJiUzBHcnI4aVNHZS9FYkRSaXdQVlh5SXg0ClRBUGdyUUh2ZkZUVjBrMVFldG5Z
            cmVMUjhTVmNjbmw4WmpZc2s1TXJkTmMKLS0tIHdnUVczN28wczRpMmtIajhkVUh6
            K2M2NERmQXA3ZWtuWWcvZEJKdlhkNmsKXdjn1V9yUtt1foZnCHueLsQFYG9x3VDh
            hothxu5tR/qJJ2xWUwvzb5ED/DdYskDDiPE9npBjoPEdVpBQTode+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T17:38:54Z"
    mac: ENC[AES256_GCM,data:A3dto1Cn4D/qIxadZE2PYs6k0Bx/A1bAt/NG2EotKl99C8pxohZ+1nejl5HCXdX0SbMPYsKcu9fJmwQWi/kI57Nqo3yU3XraOXEle6rEEDubO+IsdQgrpujfVu72eQS6W0JHsoYBF6f6AdC8Uqy7ICZzFl1sJWd/ZFytG17Sdzg=,iv:l5WiqCnSwswWnS/7dVlcV/9E6pvniRde/AD0CKfwq5A=,tag:6f4PZUrWjAf5bcMg2Q5J/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
