apiVersion: v1
kind: Secret
metadata:
    name: kimai-admin-credentials
    namespace: apps-tools
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:fS8N70p9P2MZdKI88mA2,iv:anDWCW9BZJ3I++iSNgkqhRTOEiPGp5lNi77Y6Xg8Iqc=,tag:/wefEYPmubRp/B79cvb1jA==,type:str]
    password: ENC[AES256_GCM,data:vHQkCU77+76BqOjcUpGwFto6hb/Y+NGz,iv:/bLy10W6qF7+EjktIX8e9UYkaeT8n7plWTshCp3YwtM=,tag:VJf+m0uYLp+O9aoDO2nVkA==,type:str]
sops:
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQ2hCZ0cwOVZqaDNwVGdC
            eVJWWWVNUE52dEhXQmhXQ2pRMmdFMi9NVFNrCkE3NnlHdmxCVXcrMnlkdkJuYWZx
            am9LVHNPc0tOeFp0bUZDMGFGZno0UGcKLS0tIGcySkJVYjNPL3ZGQWVoOVRmcmx5
            THkzQnZqanlBbkxBcENUd3JTbHNoSGcKHHwJMLPypdAkqTk1vQ5KoDVMsM0vRnd3
            lVFAmWU7SmzzVELNGnMkHEOLeAoOWsaW/ajlGmrXhyvLOJSmQnd3sg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-10T17:39:16Z"
    mac: ENC[AES256_GCM,data:I+avN+xGqnS+LJRbLmI2P/GV70REYNdvduPMF5BdfdxpZD1m3//LRfSaV86p8/9hiOOou3BL2vQ5EKjarmEAcbiuC8fEDSHdGPGONpsvH54t+6rFW4T0TMjVJ588ThH7aQ36o5JbjrJDMeQKti8e29JpUOtB8Go18+ocl2IgXto=,iv:sljIxY1Aez5YSpApVKq62SYyUxQSj7C1JNpNlMOEKQM=,tag:G6eugN/ebPeV3N1Ze8KTyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
