apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - store-basic-auth.yaml
  - kimai-db-credentials.yaml
  - kimai-admin-credentials.yaml
  - monitoring-grafana.yaml
  - monitoring-oncall-grafana.yaml
  - notification-smtp.yaml
  - notification-smtp-monitoring.yaml
  - alertmanager-discord.yaml
  - alertmanager-discord-proxy.yaml
  - alertmanager-oncall.yaml
  - oncall-secrets.yaml
  - oncall-postgresql.yaml
  - oncall-redis.yaml
  - oncall-rabbitmq.yaml
  - linkedin-feed.yaml
