apiVersion: v1
kind: Secret
metadata:
    name: linkedin-feed
    namespace: website
type: Opaque
stringData:
    LINKEDIN_ORGANIZATION_URN: ENC[AES256_GCM,data:bkBaJ5WmiZkrYxXz9jKF8xuVGYkhLCS8Di6lpQ==,iv:gNq0Lqrb7cayP/vmib270mq5yTebnaSMTc/hPwVaEeE=,tag:HFL00nL8Z2Ihpc+ELbSgDQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdVovSGREWWlzSjFnZEk2
            RVVHMG9wdDdCdkRZQ3JPMkZOMzlzREdpOWdVClU1djFIWXNXaWF5UGlPelNaNXhy
            Z25TaHk5WkIwbDYwL0pUcWhKNFRWQ1kKLS0tIGRtRkZpOXB1c0wxOFdLWTA2ckdK
            ZFRPcVd5RlVnbUVqQk1EQUNhS3BWZ2sK4GBxILBjiVR5a4L6+Xxg+GhLZq9eMcR1
            KXlQGYEisTdharYkil7lPwgwy8yGBECglX7r8Lt5pEKsBs6YNTP6pw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T15:41:17Z"
    mac: ENC[AES256_GCM,data:cGuXi6FDbEHCSZ4SXSHGJFNCKE4Sf3a2JammwAp/QqllrZQM2HUfKafryS8UoA2U2K4CVAjYJaC86+BAh21Borhey2aGbxABASqWTM/0rm7WeyLseXFEBL04JoU75iP/COL3HiPZdnTN63Bcrm8NKCMsKD9DAP4BccaPwF/d3FY=,iv:TRKgiuQLiGcUuK7DbZpQ/akPrY6lL69Df8S/H4l1aqA=,tag:Bo0moyaejcBHrhvy4L5WFw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
