apiVersion: v1
kind: Secret
metadata:
    name: monitoring-grafana
    namespace: monitoring-grafana
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:C1TKsDU=,iv:oTgv7n5nmEngaXUXoTyRIzFXMpgfHaQ6ZUhdHscGdnc=,tag:TBQfsVIk0WrmiI5Y6EZZlw==,type:str]
    admin-password: ENC[AES256_GCM,data:X1m5WN0tDuydOwnok3w0oHURDbK2ZmxI9zbHdoHVV3Q=,iv:e7GvsofikV8BWhobZeIpiu7yYhGxaB8HbeXM8x+aec8=,tag:3KnVrFITyjNBJUBHA68iBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eEFyYWJKYldrQ0tQRHdR
            T1k5blNPdW9XZzlWSXQ2KzJHb1YxcTVrdWtJCkVuS00ySE9ES0E1dVI1ekdMelpV
            WTRNTFNEZmttL25PcE0zMHhuTU04SncKLS0tIHRreUVScmRrd29FUzc1OHUwRDVh
            VTRUTWg4S0hJcExIYW5waDZPc28wREUKV3kcyOG7g0uEC8AhPCROhoKNI7NUsuGH
            16A5EKWlKd5xMCavY6DKruyroNRHPOr9n+YId1PGGEIsXhruqP40zA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T00:06:49Z"
    mac: ENC[AES256_GCM,data:R4fqMNgH8VLR1/40HVpXiT0ehrj29iqdoKV5sZXK/aYOgW87HMRCWe0RH35y+88quZ2iyfYZsZvT2Bu4MmjJjJSv4QMJqegtav71/nshEN9XRGclc0mcwfzSOqeebleyieZJplPzaTP7hUxFGo02TOmYdt3FKqlNfEsArkFZYcw=,iv:nC3tSeZ4lu+VLG+xwZNOqVQ5PGwh2eEsTftxajd6aB4=,tag:RD7Ay+EpAAZh0lFHT5lD4w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
