apiVersion: v1
kind: Secret
metadata:
    name: oncall-postgresql
    namespace: monitoring-oncall
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:rcmVO5UdCHrVe57e3ZcNDFjsIjo20CvKQ4TOgK40V/g=,iv:nc9VbWDmd6B3Z8BFny85mQDJv26aU3mrFoGj/P7mAQI=,tag:XnCNat1nG3Kqgvxsr75AUg==,type:str]
    password: ENC[AES256_GCM,data:TKh/ze5qvhMiCVxbzEQ90v3FLpMhW7PtwZDmFrUtTEY=,iv:1QUPut4nbFhpa+NLWhYmrTIb3AFFafnlLXHTXfV6fyw=,tag:HbbLK2lb74WK+/qWleguSw==,type:str]
    replication-password: ENC[AES256_GCM,data:wDqGkpxxmMSxxnJdKId1uvkOSVziQIsPPXU5msgnAiA=,iv:ejlk6b0EbEgw7pWT9rdU+NGEwmnM+fiIeX+ImKXc2v0=,tag:1LHvdROduaExhFZObt16pQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6aXJadVQ3aGpZOW0wakJQ
            UkI0eE8rRjg2WnhjT2liYVlKbENTdGtRRVRzClFOVEtYNkQzWkdMalhlVGJJSWpn
            MTVrbXFTMnEvVE9XSlJSc09QM1hLUDgKLS0tIHJjamd0aXdqZStnemdZQXYzNFdI
            TER4QWhHVUJUY0l4VUVNa1d5TGJlbWsKHAtQx7A3z0YApixssPPaviz7EOmg9pD+
            GhAh0CF1z9qcXYPVtZv5NsomFqWou+x0AEpaZSsbAEgJBuNSSh7BtQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-12T21:21:32Z"
    mac: ENC[AES256_GCM,data:CCL75Bc8gwzJbh8u22FIFOEtveJ49Uzfdn3TQD06bCbrug5DZA5NZoT2aCkNaHVdbTxlP5Qkjo7RtROKLtGfg1UFUD4rU1qGfcqHr0p8+QCL8Q8Wl7DR4O4kiepBFh3VMttbv/Sx11E2HbFOGXTMiydEWFtJ1/eo1FRVml5pQwI=,iv:oRKbcOc+25qUELnkYqq1s/YLGQXoLccJcWtFnVx2tvI=,tag:+uq+EvlwlGoer2drx7Taew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
