apiVersion: v1
kind: Secret
metadata:
    name: store-basic-auth
    namespace: store
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:oGuDBcaOMLuaNDhd2KHFphFkJU0fPwDtFymL2zmgwDclLIfjq+MBBc0JV1351qCzn9QMH4RbD1n7BETSbrVv+T1VKikUfAw/gWglkYi7ssghsBYdW63EKtMA7yowls0=,iv:vGanIBSU73h5BGRfqKOH77UZqpDss0alBtMC91ivIOY=,tag:0+GEb1pqZFD4rccJN+tqVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKVzBRbng1RytEUmdVdGFy
            dC9ZZHlkVERWSXJsRktnT1pFRHVWSHhoMUFRClFDVllreUdhVDhJekE2WFFZRnI0
            QzM1ZThObExvU296SjMrMFQvcHJWUEkKLS0tIHZrekNBc0JlQkl6M3VVYXZXYlhr
            TitvMXhhZ1VOeGR0ZHdXRXN6dThVZXMK7NqZswlVE39EvhttsIV+y6jerusaFlo0
            G15LsK5k0QZLBPb6A5f9clvBDw/rrtqdb3CBt9VhbGiFoMjuwwpnmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T00:31:53Z"
    mac: ENC[AES256_GCM,data:/XUKlEkdO4sR6sAoPH+LspQH0y2OVQL6q4CzOCq920UpM7rDoi47NgjY/39MiwTNvZxiJ6P8WCj1ZqfigE8PJCeX+qYbuK2XGgdzkzyWoDzRbgYm2QIXCXyAXb+N6d3jMfb6QPGtBYMrZsWrdxH9iTnw/nHoEGmN3bqxmEeNazQ=,iv:nGCyPZolm9V9TaMAywSJKVsi3B14OAKqyt85kyt1jwU=,tag:1nF0NsLEhSC8HfM8XGL+RQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
