apiVersion: v1
kind: Secret
metadata:
    name: store-basic-auth
    namespace: store
type: Opaque
stringData:
    htpasswd: ENC[AES256_GCM,data:iHL/9pNhW++DkNVXsyy+0v0iP9IIr7D1XPS9/n5PfSJld7b82OE2jn6icw==,iv:zVDJ4WEBPK/hGWb9gJ3PMGgAxTALo9KRPLGotKtY6FU=,tag:cauWLNmJpPTZhaSfVdZ+rg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eGxIbHRVckhzZS8wN2pa
            SThxVE83THRqVWpNS2ZxekI5OXNoWUJIa0ZRCkROZzVkNkNSUm5ubXZHQ2d5WGxC
            cSsvRCtnMW5pR0xmM09FU0JPUysxNkkKLS0tIEV2SGpBN2tQVi9UcklLMCtrK1JO
            aFIrTmxCZTkvY1ZuNzUxd3dEYjJ6ZTgKrZNdi5KYzDL20Nn5/lH/pD5mQd+fxS9K
            LASkMKt8UdNfcM4GDBHYM5Jb9zhHyJDoTAt1qoILMoRuvxzAVdjafw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-21T08:06:47Z"
    mac: ENC[AES256_GCM,data:RC8UbZhSkB1R7x1I0Ap2NrhPgHWbfub++tPMNEsYTBnzzEkZbwhMmnS6akMyND/crITED2rDuwS7gyn9xDVjYO7B9SxJbAlWrb1gUzWFjo766e0tNtgzvVJU1kPX+joNAhC/moS4dI/MVpeKX9z1SB13eBRlFFmTvfWWIdy+zTo=,iv:apPcnXfO7Urzj6297luYdeLS0klLknY9Ga4/NEwNClQ=,tag:Xlg8We6Ht6wAa9WF0IfXxA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
