apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: "Enabled"
data:
  BASE_DOMAIN: devsh.eu
  ENV_PREFIX: ""
  ACME_EMAIL: notification@devsh.eu
  NODE_NAME: devsh-k3s-prod-node-1
