apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../k8s/vars/secrets/monitoring-grafana.yaml
  - ../../../k8s/vars/secrets/monitoring-oncall-grafana.yaml
  - ../../../k8s/vars/secrets/notification-smtp-monitoring.yaml
  - ../../../k8s/vars/secrets/alertmanager-discord.yaml
  - ../../../k8s/vars/secrets/alertmanager-discord-proxy.yaml
  - ../../../k8s/vars/secrets/alertmanager-oncall.yaml
  - ../../../k8s/vars/secrets/jenkins-prometheus-scrape.yaml
  - ../../../k8s/vars/secrets/oncall-secrets.yaml
  - ../../../k8s/vars/secrets/oncall-postgresql.yaml
  - ../../../k8s/vars/secrets/oncall-redis.yaml
  - ../../../k8s/vars/secrets/oncall-rabbitmq.yaml
