apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../k8s/cluster-issuer.yaml
  - local-path-config.yaml
  - storage-dirs.yaml
  - node-exporter.yaml
  - rocket-mongodb.yaml
  - rocket-image-automation.yaml
  - rocket-image-digest-rollout.yaml
  - rocket-privacy-guard.yaml
  - rocketchat-helmrelease.yaml
  - rocket-ops-scripts.yaml
  - rocket-ops.yaml
  - tailscale.yaml
