#cloud-config
package_update: true
package_upgrade: true

packages:
  - curl
  - htop
  - git
  - gettext-base
  - ca-certificates
  - python3
  - awscli
  - cryptsetup

write_files:
  - path: /root/bootstrap/bootstrap.py
    permissions: "0755"
    owner: root:root
    encoding: b64
    content: ${base64encode(file("${path_root}/bootstrap/bootstrap.py"))}

runcmd:
  - mkdir -p /root/bootstrap
  - curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik --secrets-encryption" sh -
  - echo 'alias k=kubectl' >> /root/.bashrc
  - echo 'export KUBECONFIG=/etc/rancher/k3s/k3s.yaml' >> /root/.bashrc
  - |
      bash -c 'set -euo pipefail; \
      ACME_EMAIL=${acme_email} \
      CONFIG_REPO_URL=${config_repo_url} \
      CONFIG_REPO_BRANCH=${config_repo_branch} \
      CONFIG_REPO_PATH=${config_repo_path} \
      GITHUB_PERSISTENT_PAT=${github_persistent_terra_infra_ro_pat} \
      GITHUB_BOOTSTRAP_PAT=${github_bootstrap_terra_infra_webhook_pat} \
      ENV_NAME=${env_name} \
      LUKS_KEY_ACCESS_KEY=${luks_key_access_key} \
      LUKS_KEY_SECRET_KEY=${luks_key_secret_key} \
      LUKS_KEY_URL=${luks_key_url} \
      SOPS_AGE_KEY_B64=${base64encode(sops_age_key)} \
      ALLOW_FRESH_BOOTSTRAP=${allow_fresh_bootstrap} \
      python3 /root/bootstrap/bootstrap.py 2>&1 | tee /var/log/bootstrap.log'
