apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:0j3Wx/RFwRvrlS4t6GBCGWMQoAx5BNjLJn1yXKFpSEvSmm0FQQExv3j1/YpQbobW+2hIQ7+ueei2TMcWY+XVRmQHc/3aBTO5rtzqHdvE+ZJsaLQVruSlKg==,iv:i2+MBGakq142tWM1Hq10e9U/7VzT4yDKYfnxrNAs/Dw=,tag:GE+m5yHiXa2wVOeyLmmE/Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwS21WUHk0alNpNVc1TXdQ
            eUVBWnFSaGZlYnYwRVJJMjVKa1RoYXhtc1RJCndGUEFpN0VUQmR2VGNhQXBsenBK
            Mi95ZWt1RXlaeS9yQkhqMjk5cG1QN1UKLS0tIGNBTkJFOEUvLzg5Q0g1YXFaR3Ux
            cnpKN29uTG1sa1lVVWtjWVdXeG51WkUKUOFhUna6EaSW8ssr/gnHpWreWR/KmhUA
            O3ixsF6iCiJo7k/gNyzNLGLJ5+3H3H1o+7lLNlIeeDXhffnhQ9KSzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-15T12:24:18Z"
    mac: ENC[AES256_GCM,data:VmCn91f+4YaIt0g9FC1czIQ2BMNGSegBLotCv02CCyI9xyrxZ1wS7yV6v71S3FwYpYN3E8WTMT+y8HnlzbL1a3wzH2KZI6+iCUJleZSgOeQWt2yFZdxZD/TDE/CiGJ3UFi7XsF7pxtBChcnmVzvZecaW/TxC7z+9SI6h2WV60QY=,iv:Q+DE/XsxtGVVundYiJb35OwWr0J9oXg7x3fOMjznNOE=,tag:wGfzdNZskFqdNO+tJioTww==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
