apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../k8s/cluster-issuer.yaml
  - node-exporter.yaml
  - stoat-config.yaml
  - stoat-ops-scripts.yaml
  - stoat-ops.yaml
  - stoat-workloads.yaml
  - stoat-ingress.yaml
