apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../k8s/cluster-issuer.yaml
  - node-exporter.yaml
  - jenkins-config.yaml
  - proxmox-runner-platform.yaml
  - proxmox-tunnel-server.yaml
  - jenkins-maintenance.yaml
  - jenkins-workloads.yaml
  - jenkins-ingress.yaml
configMapGenerator:
  - name: proxmox-runnerctl
    namespace: jenkins
    files:
      - ../runtime/runnerctl/runnerctl_api.py
