apiVersion: v1
kind: Secret
metadata:
    name: authentik-values
    namespace: authentik
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:dDcP5Njt1SLypiTp9RBgL+ytAvmzApMtqDJSq1BZe2W5hELin3AfcXZ89EeSkXz8Z5nFeaY0DzXnymQeqyOZQLK6jQzbpTJQSTg1cFf5pOjddJqmv33IftyXKzbOCdym3faQM6p+6ScggG0vRyz9RZvR+NC5ffy6sC2Kvhaf8xkqY5OWW5XMmVRgNmgSg8Zq9BZc1aAlnnvVW+QjPGKhy6nm6wn6LbbnrUORnIh4V3szAsmbvTHTN204UHtjq5P8mUc/yyfIJlrPN5WtwYitG0UG+CQvszFIQIznK1ekX8JnZ+3YTw7mVDUCQjABRfK89B5+r2z3UY4dPQ==,iv:znMxsSBZ6fThy9vhePkGmP6ATE1h3GNcLqc5Ipg7Xbg=,tag:7V0AdtmSekJ9ct1Qb3zVaw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXS25IWDhwLzJLVllwcFZG
            V2JlQUhEUU5yMHdZcHRvbXAxTXNxRWJwWlFNCk9VLzlRTTc3bTdnSFEyY3JRVVdm
            dyt2QVY4SFMyWGR2Ny83dlkwcFhST0kKLS0tIHNUVnR2dGtzYzMvRUdrVVRscEJ4
            aTFtQlAwejBUb2RaWlJqUkNBcFF0bjQKWTp7+kqCLnYdIXxsZTohCcGPp9K8o5oe
            0mjhfLiQ9t2n/ONutB2PQ7XhDJKgjwmgAmxODphQOIqnLg+M4KCNiw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T08:30:42Z"
    mac: ENC[AES256_GCM,data:jYmdZOivLt0xPBAzGJoa7BY5zWWw0f8nX5eTQWRqpgFxfX7cYJQtKoIqyk/2iotzwFzEBVG9yYcv7Z69ae7vcWWBeycgTL5Hww1aS9LXQMQybSILQvI4L0SfLyogYY5BV9RY3zwXFe+cAcxwFet59Oq61GZFz1T3lNTCzujCLxs=,iv:uh19QuZz38jDzmKczdaA9E0famPu5RepupeqBPCSD4k=,tag:q2GUxwmBmRRGAEx6xOze4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
