apiVersion: v1
kind: Secret
metadata:
    name: headscale-oidc
    namespace: authentik
type: Opaque
stringData:
    client_secret: ENC[AES256_GCM,data:vKkiI/vi4O6kDrtliXQcuggluYig57hCXWQ9YQrjaR2AKWM8ThgB9H0wuI0CWTsDb4g7/2i7L/CBIhWfZQFXcg==,iv:2j7MxtPlVGou8f6JXaFDNajPnkRVCw/TPFHKqovV6UE=,tag:zTJUEY7uFG1Gf16np742Mg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrK0JGUWlvcXRGS2NTUnFs
            Ynd1WDJwZ2hBOTBOMlc1S0xhUnNyUndaN3dVCmpZbEV4aU1jU1ZwUm5TS0ZMK01q
            QVdrOWh4WXVtem1yV011bWFweWtobXMKLS0tIGJycXk1WEhhSTVmRjE3Mk9vd3o5
            NHUvcTJqSjh0eDlEWVpxOEJJSzZvQzgKedgEUDMU/C8WSF0wmURrj4YgeC+CAu4t
            24UZdKTVydBb5CRGufJP0/Hf8aB6020rMdjr1Z/z6yCcA5s8PupOhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T08:30:42Z"
    mac: ENC[AES256_GCM,data:GsuewGjTC7YyUM4W/2NkJaUi5zl3QlMMfykdDboW1GdPXcZ0LdbEDwBsxanFym/g4vK3axX6WA6rEJpmJXpuWkUA4Da8eeP+J7UxbWNyUmtPOIvplxLflRDRZv3Np9PQCw80RAwMLIo6qsSo66MvXgm1YWrs3qMIsLQ/NNrUp08=,iv:ecpbbWaroOMr/qgMqX3n3WIzSOh6bLsL98hqM+Iqxbg=,tag:WFv0y2zvzLAmyH0fCcyLgQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
