apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik
resources:
  - ../../../../k8s/vars/secrets/notification-smtp.yaml
  - authentik-bootstrap.yaml
  - authentik-values.yaml
  - headscale-oidc.yaml

