apiVersion: v1
kind: Secret
metadata:
    name: jenkins-store-publisher
    namespace: jenkins
type: Opaque
stringData:
    RUNNERCTL_STORE_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:miQ2q5TiFTw/RnRPst1QlQonDgE=,iv:Y6BdLH0hBvJiQUSydHyeUNnBdayxibaORwDCBKRll/g=,tag:9BVvDh7r8uymb3uQxzzi2Q==,type:str]
    RUNNERCTL_STORE_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:mE+W7HweSjk3E7pEbgizgn5YS2y+UWy8/fIn6KVpLtQxXnAV,iv:BKL/0yeLc7ohcz4l7eTlxp3jRqG1uDhy5FrCKKb8tJs=,tag:bygenIyUEYMO1wcYqaYhlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVVF1MGRicXMxRGJrL2Fi
            bHFIRjVUTVJFQUNNeXJWbkxuaFdyNEZJWkhrClV0eVVFTWtKWXBtY2FucXRCSldk
            bEQxSXJ3OEFmeVQwaWNGVWQzYlNRMk0KLS0tIE5yV1RXY1AyaXhEbUVRZ2FWdTVB
            Nm43cW1ndGJ1dXZMbWY3bUllcmRwOE0KRyDtmuuQ7IKIxHTEof6DnCkHOcEbJGte
            QK+dKCshbQ9D3gTUZrex1wH7Hal/zJAPwN8zR3NO6FmOiEWL3/vphQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T10:28:35Z"
    mac: ENC[AES256_GCM,data:q1xHNKBpAacbgOHfa2OasskLtwtMRdOwjqPlz+OXJtZvMr9JSk1SAc5EV00wkuRXaXDJm58gnFa0lff7CbCARQ9S6O8tBIu1xXSgDP3/KR6/cKk9FVJIJSr0+IJLX2+dV+JnyMYw9tnDpAj55V3HJrWILHAikAp2dXjLu5Q5YfQ=,iv:yp6/we+oLpUGQt3g4LFpfmLQkKABlWIhgl7X0ERFrk4=,tag:Jo5dVbI00OxKwBsWSRZjLw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
