apiVersion: v1
kind: Secret
metadata:
    name: jenkins-admin
    namespace: jenkins
type: Opaque
stringData:
    JENKINS_ADMIN_ID: ENC[AES256_GCM,data:c+RgCa4=,iv:4pFYn3F5MXBJMdBaDwAfDgcR3z+2I/z/9Vxki/1jFvk=,tag:IdPfxyNcgfT7LMpCXVylHw==,type:str]
    JENKINS_ADMIN_PASSWORD: ENC[AES256_GCM,data:34XBCe9vLw1fapcoRtMNZOtiSRlW6LfoQ/WFQGJ4XGVvaSSEshopa+kkq5kxGBRi0/gLImrVpqrjb7q8ylfKXw==,iv:KAtfa6Om4+vWAFN1DmxI7ho/B8WgNmzQNDgF6XxFBRk=,tag:Dj1Lba+FVc5d7EKpJa2inA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUTNwVmlnZFlqemJJWEVr
            VDRlcmpTZU9JWjJRd1RnWGE1QWwwVkxRcHdnCjd1R2VjTW1hNmVYL21aSWx4c2NI
            NWlya2pONm13K0pzVGtBMDRyV3c1NmsKLS0tIDJuOHpsYnVCK1craWs4Uzd1c1NI
            Z0tPTFNqZkR0cUM4aVE5Wk5McGpvNTgKslRuROEzLgSBANLPYbBCG3CEnEy5Uobd
            B5MIFw27fcdBo1yrR/LBJ0W9Nh/EGMQvNYUjuPN6ohVzbNXsT+0mmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T12:08:34Z"
    mac: ENC[AES256_GCM,data:0PpDomWfEuy8GMR0j8YR36wzft5HNW/4LMeQOZZS8BRf4iPN1buLobEHBFqVsWWssboO1N1rI93qeNlIGv06Fe4SKP6pJ7U/8eNXKz2zUdhVX4r/Y17s4ff2lR+xnIdGe5dHM3pJMuSZiCTnuN1igiP6/+tepcl9CxmNdoeD8/c=,iv:M7aTgBo6dinOf1326p2vANe0tEQ8A5oDXAKeBbWJXuA=,tag:1qX8zP+xn+m/ukvEErw2Ow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
