apiVersion: v1
kind: Secret
metadata:
    name: jenkins-admin
    namespace: jenkins
type: Opaque
stringData:
    JENKINS_ADMIN_ID: ENC[AES256_GCM,data:c+RgCa4=,iv:4pFYn3F5MXBJMdBaDwAfDgcR3z+2I/z/9Vxki/1jFvk=,tag:IdPfxyNcgfT7LMpCXVylHw==,type:str]
    JENKINS_ADMIN_PASSWORD: ENC[AES256_GCM,data:34XBCe9vLw1fapcoRtMNZOtiSRlW6LfoQ/WFQGJ4XGVvaSSEshopa+kkq5kxGBRi0/gLImrVpqrjb7q8ylfKXw==,iv:KAtfa6Om4+vWAFN1DmxI7ho/B8WgNmzQNDgF6XxFBRk=,tag:Dj1Lba+FVc5d7EKpJa2inA==,type:str]
    JENKINS_METRICS_ID: ENC[AES256_GCM,data:74yBsi7PAKy3HM0mKFioxYJe,iv:EIJz3E2NGSmLj5xMiOnpjyL/nMsk2w3hiNV0zOWZ/Wg=,tag:I4dXmV45fEeNSyyjlp3Hfg==,type:str]
    JENKINS_METRICS_PASSWORD: ENC[AES256_GCM,data:+7Gnm7bmrvFuCIZz0MBRLh2ck9jygKzL8pbWFktXSu+feHD+8eiXwVBup/1IUvkoH6dAlPngpcajntbkQUhYaA==,iv:Fu6b9b52xkV7aKki83GYvWaJRsPgTxOINY0gz6Jr3yw=,tag:tad58OCMzzXGcvO2HXSblg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUTNwVmlnZFlqemJJWEVr
            VDRlcmpTZU9JWjJRd1RnWGE1QWwwVkxRcHdnCjd1R2VjTW1hNmVYL21aSWx4c2NI
            NWlya2pONm13K0pzVGtBMDRyV3c1NmsKLS0tIDJuOHpsYnVCK1craWs4Uzd1c1NI
            Z0tPTFNqZkR0cUM4aVE5Wk5McGpvNTgKslRuROEzLgSBANLPYbBCG3CEnEy5Uobd
            B5MIFw27fcdBo1yrR/LBJ0W9Nh/EGMQvNYUjuPN6ohVzbNXsT+0mmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T19:18:58Z"
    mac: ENC[AES256_GCM,data:n6tE6lPJJTZc4i9pkfqPO2j6IKYzKYwVi+a9PLmqwYG97G9wZyw+87wzSf5VT34RSxyYB1X0ntey1BIgtPRZ14fPJwrYvzixrMqGfROBGl+Aod+kZyWAiwXUmqFl1NCS0gitkVA32wKB4U2HAtlO66A04+Gzeig/WtGfrVMxAWI=,iv:vqA7PQ0eZXSTJvJ+EKHUF276EtwrnUyNCA6UW7Nb/9s=,tag:eFTCpoQ+7kSNTb2JrVjrvA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
