apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins
resources:
  - ../../../k8s/vars/secrets/notification-smtp.yaml
  - jenkins-secrets.yaml
  - jenkins-store-publisher.yaml
  - proxmox-runner-api.yaml
  - proxmox-tunnel-ssh.yaml
