apiVersion: v1
kind: Secret
metadata:
    name: proxmox-tunnel-ssh
    namespace: jenkins
type: Opaque
stringData:
    ssh_host_ed25519_key: ENC[AES256_GCM,data:LwA05dO1Qf0/BkGSFJZYu0FY8XAss3XIDmdgwZMfjaRve9q5qRtblYECUfO74aeWmUZ6qg9pP6e1nerrtkSNjYZkc3lIP5p6yyma9i9T6W4XWATk2GLYSbgvXY2XDRe4geqNARs3y7cjvLyWEsShfBjlSeELme4s8Z3bchh4eTFUWiWUdHJeWLb3vkoc8IMG7/VWH8rzZxLNAIeLEFQreSvbL6wHdzAcVZe6waZ+KzFDgn5zrOKJEvhtW63Lk1OBfXj/K/jHqTlLdFPLb0NPLHwZlN8r1fdSzjGH5M8XLXI/1K1zhSK/vGap3fMHN7HoK5JPxVJV51s/Optj6NeZ7n4PqO++pypUbty2ic7B4s/2kAm7oqxnQNM9HW8+YP+jiQQviw25gVnC6Pj+tk1zZvDJSPvigjeMxgP1UdnNmbBw8XjwywukHqHD8F/u1OLtqWdjR+7RVykwcZODxbNGH7lZoqtK92pjew47PWG5d4X7Y4lt5I6omMHiLkK1ZdgtPiRiYBJ+5aQuIxZsCNzvAAKzmM3Lxw1Fx/ydfQLvmdT9ZBVA7VtvG7/cc3qtEUY+oU8X9qfbNl6pY/45ukMXkFh5sus9y6gDYE1pOzVhGRM=,iv:Y1lMRUkr0+SVWH8eT+5l/Wi4VSW8R+HgdNkuV3dTtpE=,tag:Y6sgu+kYO2LTuTgTiUl4ww==,type:str]
    ssh_host_ed25519_key.pub: ENC[AES256_GCM,data:zYVjH+ZRR+GSzpPK2buJPuqchLRFVhWKzcFLBvl0ht05S97eQE5DpemzyV7gcCExe4cpPbzhyzMR1J/2vFzPutcMeKsHRK8W01ZfP3ckQOiF1/JGv9NtfsuFsxW2vUJtWIu4BYQrhsfOd1ji,iv:6sDhHrlkgASihkg0and0lsyEDGCNM3YiyR5Q3d8gPCM=,tag:8Osb1zjRY0Y5KC5kt7dSyg==,type:str]
    authorized_keys: ENC[AES256_GCM,data:grLErE59Ci+B84nffzppehkNVO9ZK+sMc4dLKw9BJ+tNsA3CYEbCI+0hEUBoHeZdqAPauYcDktvurAlvMhL+o5ZxIKZyvJCbazsXfrF4HO1egseQ+TpYXogGfDHAzK/+3xPopzF+QOhI8+WtL3WTfjWfDXNcQIX1+U1xwcpX4YuONVXqKzePmcSY4EK1fbfZtVgrpixyL1GdStzUO/j73ctyE5R9kEkEXGFP21nDf/4A12WvwuEU3E4EnXrIR4xc0faxi6ubR51dkaa1GQ2LZmHFCckw28ov2/+nz/veXdbPMfUxtF/i4KvLkET3Zkl5rueq+oxKog==,iv:Cic7SYRYW63cweDdx8bqZUx2iFHzKSZLFCNv4HmrZ8c=,tag:V1bPrs4yRNngMAkau9dL/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbll6eHgzcnJNc3Y2NFRZ
            a20rUmp2c2k5V1hpMGEraEhOYktMRzNwTEcwCjRvOU5GOWM4TGJwbXlwSE5Fa1ZU
            SkQ4REd3bEVyL3hIclJCOUh5OWxTMjQKLS0tIExPZnFyQTVxYU9lVG1Ud2JtZUda
            QVNLeUsxSkhLczl1NXFmUmc2b3hBcDgKyuGgpfkIsMtQhV+lhOJ1q2RL4lU2ME1J
            sEFHOoe2wVcS0rCLZKzCEuWZAZ1qG8iEwkVNKhU/+p22GTStDX4gFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T13:00:11Z"
    mac: ENC[AES256_GCM,data:UQsoDLSFx2dS+FccC8LiySLYhxT2c3OJUMDGLF9N4mGU9Yszcbmjt0XxPX+IqFTzFwMWX4wepnG/TwwbfwHmS8PWzSG/YU8skcQXlaOAqXUnkWESNHRYoVlYnZuMt0uyLmA3WMhjpNpe94bj0CXd8jCy1l/wx4p2xLlAnj5lDlQ=,iv:gleYHv8yGyZys+ILUErUiDBzug8/dhCA2LEEuBwa4Yk=,tag:j7GXIiwQdXbvXCBG9HIRqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3