apiVersion: v1
kind: Secret
metadata:
    name: proxmox-runner-api
    namespace: jenkins
type: Opaque
stringData:
    PROXMOX_RUNNER_API_URL: ENC[AES256_GCM,data:Nrd3/OjVGQZiv+SWfqJ0HyPBk7gVKcs4AjC0efyVO7/3,iv:2VFysVKtCIfwU+e6ZOv6x99H6aHQg8ZVNmtMkFtR36M=,tag:J4gSGENFJoh7iNYCyFwm1w==,type:str]
    PROXMOX_RUNNER_API_TOKEN_ID: ENC[AES256_GCM,data:cWtXrWKXwNZWDh1QQEySBzA3q/f0L6Fz43uUxDrK3Y5FNGip,iv:cVY2FuwV7kt/g26+LgLY4qoOB3G9aH15cf8eG8uy4d4=,tag:1+arhuw1Baj07AGKOoe2CA==,type:str]
    PROXMOX_RUNNER_API_TOKEN_SECRET: ENC[AES256_GCM,data:goyAdjlyXyqjiKIn70LfFABHybHD3pMJdgzYiQu2UtbVk4vjMWrBDFuQD3O7ybyh,iv:HmFwNRA7S4tzyGCg0BVEpcSgOjNn6X7IamlUNkCuN/U=,tag:vrxlJ++zzrnvV2AB0/FsrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQ1orYUlScFpVWDMwR2dT
            UVZyT01ycUFVdlMvSXgvVmFuSEJUckZFTFJzCks4NHNYZXI5dDI2d2N5VWtLYnRU
            THZIaXg1dmNDQ2VsY3NIanp1bEpLd2sKLS0tIG9Bc3JpU0krYmtvbHVBeW9NYkRp
            VjkvZENZWi83cHNCNlZBM0NJRXVWTlEKT7ivUytvn5qlnBBE/HnYFhwH7SoinawZ
            6HKAqZNdc9C7HJ2hOzGHce2RRRU9cC5mLC7KFGPS9pzc0y+Qk6A4CA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T12:10:05Z"
    mac: ENC[AES256_GCM,data:hAqZ5oKGrZ4pXL6cpM/bFKkQ6G+1XeL2b/lwgqCYHQb8yK/tgUZRNhhTtaM1+EpXHqw3w7cc36ZaYw3cioWDpBp+BykKFH0yD2sy8H0N9YCwe8Q9nyKv0s17nUbON2RZsI1/6vO859iprdMdPGru9mPF4Zam6j9I+dwN5tLgRcc=,iv:Ouh0tKgyQKDy/rITAAyo8RWnGvcUb1Gm98Uo00Kmyzg=,tag:Bx3oCFhrDWtgbGXMXSoDEA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3