apiVersion: v1
kind: Secret
metadata:
    name: proxmox-tunnel-ssh
    namespace: jenkins
type: Opaque
stringData:
    ssh_host_ed25519_key: ENC[AES256_GCM,data:owQ+dv3kRyQQ2P+9vNB4V1YhOl2K96BhQkrFWB6Wg8Jrve2pSPE7HgIILkawo3ntsZLs911rhonEiATYLUucMSWoJrmvfNr3k/cZ0x8XQen9VS6+LCeQfaIExC/90x2+1+9kUcu5X/htWpf94UwNsVmKELeSUGir24v89fdxqokfMHSfgA3tvBa+MWCL/Q8PdyJ80SS5aQnXu9SgNA5Uc4LW1GTXsQU/pEV54IoScPR96eRU1Yk48Ax2z0SN182EA/KamowVcvFmJzQIdxiNv5huAJauOdpDo6mbJOjEryhIKk99jHHjk8+mtJGiVYXUnzR+9mBos+Ms9PwLKK1svBwBXDTSZMvIyZ1qfJwOJQ6fZp9yw8LcdzaeFdyb2BsZ95zFGcK+NoIjiwicjPaYB2hblUlPBd3PsCRrhvXPFK+UeW8jMHCkt3GZlCe2U3nt5K00qKYylYnNJklW1F2uz+Z7eM6vFPgx82mOaTZKdm+G0R3CruzQQEllNr0fELIeqT8MG2hw/EWAcitJQV87zM9/Nd54CfYOXlhqn3M7QcMUUJt6Xpg8O8UslqfsDdF8WsU9og7YZj8kByUYPqyCkttTezm+4ACGb6fsylp7bdo=,iv:302Om56LHYmvpVWoto7QFroxWmoz8kDWPTi8+taCMxc=,tag:pJe+Q3XYP4kgD9zNQ5NbGQ==,type:str]
    ssh_host_ed25519_key.pub: ENC[AES256_GCM,data:dAfUoItGuuvZqkUssN6M5SCzfCzR4VVMPpF1Ok2/q8wzZdyCOO7h5RDlxVanHGOZPOqcUroHxAANmes86/Ft4NWdkbpQU0FiPLICYiU+Z3EA0L/Q8P5R4t0g0TeMHaqbsiq4CeynLLCYDKWK,iv:FodzwZcWU5diSxXbAbX1OWDwqvhT2rqEB+VFmcoMf6E=,tag:hIHLlt9Gi2pjVTmxnmF0vg==,type:str]
    authorized_keys: ENC[AES256_GCM,data:2CMueM62vwbaFYVM4aq0LrDKHlfjzUOjsk84FC0mBMeyWJUYBvitugND5pz+ypo09jw/1hWNoaMeNhIvKAtxoN+j/I+7NKVtwLdYzAtCNfmXY4WKN79KRD8c+iwZkNO89Q6qiD8IxWKDmwQpgrjuT52ah00yKRQXKVWouqj1qnJ4MeuEC4o2W0oePHFoHyOUMTX52Rt4bV67Y9RrwqMtP8IfjxCRvedmCvbtvDHUl5l+bHxbI1/WUl2PfbsBIbJUoIMs3wjVgMxbKD2hAhs9pucnkIycM8fTn+c/nfiXASy9DVLf8kpbzAdRhrDMcUMF7BKRxBPorQ==,iv:VqMJCUkg7dIktm5vYKEN3D6/bKcEfyeC70dKwqGtvog=,tag:XXeiPmXaP/9oMLa7VOG1gQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwNlZ6dGNDQXUxZU9jaTY0
            T1FyaFZiNkN0cmNyQmZWazVPYk9CYWdEYkhRCmV6U2xEY1Nucm5STDNCWFMzSjBQ
            R1VQaFllb1I1eStzTUxESm13R3l3U1EKLS0tIEp6d2tOK0FsRXV3L1czN3FmZUFR
            MXIyWXV0aHd3VnZsbFhUT0Q5YU95NGcK5GxhyVmC1Yi/NAAwqGgzDSDuVLZcerv3
            /akrWKE3g2/nlAxuA5gziS+GTlcyM7I/epyMUdBUCE5VN/s/omQs3w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T12:55:00Z"
    mac: ENC[AES256_GCM,data:8sA5wiTkISMpob3pxNXUuO9chGcK9DkVd8escQixoLmsV2OoMs6cbM2tHdhjQX0+WPpbxVTrYeYoI1Rraxz8Uaaz1O9km93I/2lNlY3bIaWPduTu4EwY/2argaOyOG4WGPh4r5U6vHjNz+NBPlMq9qmbcs3GXXnkSvVZa6jtgtg=,iv:SB99bGGqXhUh4U5bisT/DFapVrQsmzeJftdqGY/bRtc=,tag:ioS8f1VaxI/AagoK8smpYw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3