apiVersion: ENC[AES256_GCM,data:lk0=,iv:SInvyYPgqyHQ3xQrPuJYitw5wJuXqjryJKtv2IAmI8Q=,tag:s27SwAcfvnr1GEkJVBhcIQ==,type:str]
kind: ENC[AES256_GCM,data:AOA9L1U9,iv:9rUIz/OGrMCHHLbx9jPppt1g2S7SaOE8CowHkTOKdHc=,tag:d/0nft9Gk9lDnpC0jVtoKA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:S1A3s85L1a5Jcguevy/MwjV5,iv:nt5mLiJ+gNXupdgA6xUvshl0Q6TDz7/4atviMBy2Frw=,tag:LSkjyrXSMPzxmfbKbJTjNQ==,type:str]
    namespace: ENC[AES256_GCM,data:mv+wV6rpVw==,iv:FplOMrJtUMwSpB/3YEiOgtblxy55YqosY4tlpfZQi44=,tag:hiJbU2ZwY/dcqh4FJi57Lw==,type:str]
type: ENC[AES256_GCM,data:YynAG+PZ,iv:r1Khxk0Utah+mHBvwGrumGvflXJ77HfE1S80cwnXwD4=,tag:AGPfrDgc9lt5XodD/xMlyA==,type:str]
stringData:
    PROXMOX_RUNNER_API_URL: ENC[AES256_GCM,data:9oaJt+bUIBKlJBvl4VC2Ycb90FaP+F8ptIuDvPfQd7Wf,iv:vZtk3oNpEya6veQ16Hs8kYVyPCH7V+fz0NL1TWwqeBs=,tag:erw3YVmSWdC7e4zppaNJBQ==,type:str]
    PROXMOX_RUNNER_API_TOKEN_ID: ENC[AES256_GCM,data:/WE94ciaRFq/mFCrwjg6/XIpZlK5C+D8vbc=,iv:zjz4MqZ5wlR4lybIIGSij0h1rYPEaxNlTmMmtygDtV8=,tag:+WykvSSlT4Ytgtbl2fBDHw==,type:str]
    PROXMOX_RUNNER_API_TOKEN_SECRET: ENC[AES256_GCM,data:5CLtJn2YC36Mkse4yredy0RO3IjPQzff2BZgooLuvfzXxUWT,iv:T+EVuk7kol8WbnZkV2ZM1qW3fnoA8dIZYHCdp+QKnLQ=,tag:uaqBI8ZNnxutCS9rdwOLjg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eUNndG1jTnpxLzBjcXl0
            Q3FLbU9FT0RNYTJnN2hHUFJSV0M4MDhueVFRClZ2VVdjVlVVaUVWUVZtTk4yYldw
            ZXpYUVR5bFlES0FLZ2oyWTUybHg3K0kKLS0tIHRhaDJuWU9XN0lmdUZFQkI0Wk82
            cFpaeDExRlBtU09SMlVieHN4eHhUa00KC0fyeRpZbwVMDFAscUbyG20w3rkjOtC2
            5Odld/qvQ+9YmzDRF8MG5MDTc7lxnLgE8mRBvWIYLoNoxnwwmPw7xw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T11:22:51Z"
    mac: ENC[AES256_GCM,data:B9RVQwH+WX+C4Hfr4CvUw/lY9tYSO+00SHhBwv6d1O6NP86aYVuvmRv2fs5R96/F/0PyLYl/iKqwmHohZ71gGovyrO41GanyAnYIzi1z4wzxzReMU1Gf3ARBrvCiVx8SJTtiaiGb7s+grDvHUMT3uYEzM/CeUBganzVFW7MuVgg=,iv:FyPgNsSg1Qq8MdzO4YLwRHPpkIfpN/vPVu3whzM90E8=,tag:5emJ+8w4pUZ0U12lFwBLFg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
