apiVersion: v1
kind: Secret
metadata:
    name: proxmox-runner-api
    namespace: jenkins
type: Opaque
stringData:
    PROXMOX_RUNNER_API_URL: ENC[AES256_GCM,data:SuQ+zPYqPT95N5iPu42ikOSIusABmo62x4wI/8MBvk3m,iv:dfEyQitfqeexOAXpWYPHBIAdq/pz0F1diNqmLUcWhQg=,tag:hDMf2XERe30Tye6URBIjkw==,type:str]
    PROXMOX_RUNNER_API_TOKEN_ID: ENC[AES256_GCM,data:GvE1nSlcIrds57l144gD7+TRiAqdEubEZGQ=,iv:VhKk7ha2msTqkWog31vFPwK8Nol6D/5/AkV0SjUzzgg=,tag:7YE5rkzFM6ltXSkBh81xSA==,type:str]
    PROXMOX_RUNNER_API_TOKEN_SECRET: ENC[AES256_GCM,data:fCoGYWimuMchlqEzFqEOOgyztjZVcFoNK8QXCA+49fmLuaE4,iv:Ti3Lj1x7xCwy0qvdR91ziOUXZOSS+6UjXyRPXgp8Rrc=,tag:QBBONp7MnivkhY5AhrUEQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3amo3eHQxQTRONGwwZXlC
            Z3ZkV2E2OTVGQ2s0ZWR3Y0U5YUZwTDdQeGhvCnVsaVdYekZXWmwvdlp3czJDc3FQ
            UU84bzNHQXVleVB6cW1IVm9hM21oWEkKLS0tIEorS1pmdHNjdFZXTFpKKzNRbDFq
            dkkxWnF6U0tiQWFsck14andUTmlBRDQKqKZC1DRbKJiwVbD/dQJmNwg+7ZLQfLVy
            Zu05TfARFYvwAJCR4BM5fcIknwqG+8zm59bdsuPabFcWoOANye832w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T11:32:13Z"
    mac: ENC[AES256_GCM,data:KTo+tckzxzPqkfoigqbwjcWcmCoPqRYwZZSorYaJvuFfAKQoyXa9CwNiusa3VLRv6t/FmytyxRRKk7iDYdTKwVoc/sCpc0i3+9pa29aAvswOFQ3eO+l0tQ036kzYn+cHZjU4NaB7DeQGEQFaYYI76DlWtSzPteH02TRThus0nBo=,iv:lIwQJuq0jvFoY0AV9QqaUeeHETCeaY7SNtP58mL1x8w=,tag:rNyIYgnkGrV8qOTzVx38UA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
