apiVersion: v1
kind: Secret
metadata:
    name: proxmox-tunnel-ssh
    namespace: jenkins
type: Opaque
stringData:
    ssh_host_ed25519_key: ENC[AES256_GCM,data:io7QRsOljbgyIK2yKBVAmsMr5dv25OrESHsXEPyet2WjZRLam46OqOCDh2NI1i2hgMuwA5/nNHN2eS4YuOy03lDWxMarTUCw0RMvDOQvqDhGguY85R4wK2xFQZm4ZdrNCVSeiZyBNBxkwvt0p8oG6d6TSLXs9wSDV9RXsezmj6TpwNeTWKjgma+TQSwl//fasXXU1jiyCxTjmyvR4+MEn/smHvPFVyObCNXlU1eKxkxsuJcICsLxLnWokWLTxHB2RgP66OUiKNEHXoxeGGn+QK7R3bT0G6e2ZyqwHLE+mArAP1xTeY9HVbnXzHW1XhbiuQ852fqkqjP459Znj5RCOVPvD+q9pFRSrDPY25KO7dISIGIsUGldms18W22dpMu1ABoROtuXxVZw47qSVLY5Q2LZWV1bJyWab/LHUjgo/rDUQgGTUqobDcC9Kgnd35XQkC4jR/ogOo/xKZ2Y/gBTK9AcK+4fUYsexg7k5ZlENBma7eAiOilUl+M8nvcQCkrtBk88b6FgPItucMmXili6Gtd9DTKP/fORrPpf,iv:zZFLTCJVA5yoNr1CnF2aKFtcggbn7p+mMxAAaZa3+JY=,tag:wT8QRnGp3bVdb+Vvlb799g==,type:str]
    ssh_host_ed25519_key.pub: ENC[AES256_GCM,data:wOWknKdPrtoi7zU/K8s+Bckp+gSZSTYYmXr6zMcwwzPUNQ808alEEKbeEAzH3AQxCTlfC/i11PuqFJ3mBqe1w/MN2ALL4VcoKdyFAIBD3to5qxtj2SQICeF1tU1JerzGOdN3,iv:RkliVP7yeRDr92wqAeMXuLbG4Bn67Yw1Vyk+Mv6CwCo=,tag:SsGRDmx6rD/7gO7B9nAdXg==,type:str]
    authorized_keys: ENC[AES256_GCM,data:F+p5x0emA+9QLduQCZCP5jAZEUgtMcUY4wUcd2l7uN/aHHATB8dUNVTkqUxvyw8yXsBVQEyiwuJ4U6RsTFJUtQBFpE8YZ+IvS7U1r8aXCjzPiugYSUEJV4JVufoUFl5l36M9o75I04ZX34AtgwAfTupQdLztQfZmdRtJpfpVZSzKdijbeMLikjS3qUFvWnVZsWYsaO49VtOOQFLzBG4cKrT3LUaALIBJWRKR2Q9wIGTH26lx0mxMGeBjWSbZ1N41EFltwRP2KuviiKI28A+bqu+SIHWUnkqNrSBu/FePbnyBTwIXpX81L3m3fZkBC4zAxC0exHLReA==,iv:wJdRXcNB6xyAfUQ6xpJjIVYbzANMfOIWra5FdniIZe4=,tag:X3Fj72I5vZ+TFcoev1ZKVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQa3g0RUxwSGdxRHJtYk1a
            V2lCT1RnY2J4QzAwTGNNMWpHamhVSW1qK1NFClhtNWFieW91N204ODc1bTR0OFda
            OXpPTG9ZdGs0Y0NrbFJLR1N4RXJKTlUKLS0tIDZjUXowZWs5OUplWElFYmhMNGxU
            bEhFTE1kN05ZVzhGNytrMnMraDcrVGcKZt4EL+5yqFUIwa3s9nJChLAsizMnn5hQ
            7ZMdKWvpTCNxFM+MpOnRKtIMj2tzIH2LIuMJ9eNK+W59+a2Ks8Zxlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T13:13:13Z"
    mac: ENC[AES256_GCM,data:pkVu9UTKVSp3deMXw+0RDulSClGQsigYZ1kmAB0VqhNpQB9iRKrK61MHP+SCoSQf0XvyxT2myuz8U7OmmWHlKeXAoeaO8PTpPNOkAqTM/6wixPbNPJ1m6nsBW6jm68bueU5aeck8TyRc53UIgbSdwn1iWvDOO2ELESOmlYQdgzM=,iv:OgyDc8uZS4px9hHECSEcVwP5Jm6iKF+TYlvLTNxHaNQ=,tag:limlmoPLwdtwJmmWadgltg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3