apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: www-website
  namespace: flux-system
spec:
  image: ghcr.io/devsh-graphics-programming/www-website
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: www-website-linkedin-sync
  namespace: flux-system
spec:
  image: ghcr.io/devsh-graphics-programming/www-website-linkedin-sync
  interval: 1m
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: www-blog
  namespace: flux-system
spec:
  image: ghcr.io/devsh-graphics-programming/www-blog
  interval: 1m
