apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - priority-classes.tpl.yaml
  - flux-networkpolicies.tpl.yaml
  - flux-receiver.tpl.yaml
  - cert-manager-ingress.tpl.yaml
  - app-networkpolicies.tpl.yaml
  - kimai.tpl.yaml
  - monitoring-prometheus.tpl.yaml
  - monitoring-grafana.tpl.yaml
  - monitoring-oncall.tpl.yaml
  - www-sites.tpl.yaml
  - dashboard.tpl.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: grafana-dashboards
    namespace: monitoring-grafana
    files:
      - grafana-dashboards/node-exporter-full.json
      - grafana-dashboards/kubernetes-cluster-monitoring.json
      - grafana-dashboards/prometheus-2-overview.json
    options:
      labels:
        grafana_dashboard: "1"
