apiVersion: v1
kind: Namespace
metadata:
  name: website
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: website
  namespace: website
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: blog
  namespace: website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsh-website
  namespace: website
  labels:
    app: devsh-website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsh-website
  template:
    metadata:
      labels:
        app: devsh-website
    spec:
      serviceAccountName: website
      priorityClassName: prod-app-critical
      containers:
        - name: website
          image: ghcr.io/devsh-graphics-programming/www-website:latest # {"$imagepolicy": "flux-system:www-website:tag"}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 101
          volumeMounts:
            - name: tmpfs-tmp
              mountPath: /tmp
            - name: tmpfs-config
              mountPath: /config
            - name: tmpfs-data
              mountPath: /data
      volumes:
        - name: tmpfs-tmp
          emptyDir:
            medium: Memory
        - name: tmpfs-config
          emptyDir:
            medium: Memory
        - name: tmpfs-data
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: devsh-website
  namespace: website
spec:
  selector:
    app: devsh-website
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsh-website
  namespace: website
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    nginx.ingress.kubernetes.io/proxy-intercept-errors: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      error_page 404 = /;
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${ENV_PREFIX}www.${BASE_DOMAIN}
      secretName: devsh-website-tls
  rules:
    - host: ${ENV_PREFIX}www.${BASE_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devsh-website
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsh-website-root-redirect
  namespace: website
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    nginx.ingress.kubernetes.io/permanent-redirect: https://${ENV_PREFIX}www.${BASE_DOMAIN}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${ENV_PREFIX}${BASE_DOMAIN}
      secretName: devsh-website-tls
  rules:
    - host: ${ENV_PREFIX}${BASE_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devsh-website
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsh-website-blog-redirect
  namespace: website
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/permanent-redirect: https://${ENV_PREFIX}blog.${BASE_DOMAIN}
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${ENV_PREFIX}www.${BASE_DOMAIN}
      secretName: devsh-website-tls
  rules:
    - host: ${ENV_PREFIX}www.${BASE_DOMAIN}
      http:
        paths:
          - path: /blog(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: devsh-blog
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devsh-blog
  namespace: website
  labels:
    app: devsh-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devsh-blog
  template:
    metadata:
      labels:
        app: devsh-blog
    spec:
      serviceAccountName: blog
      priorityClassName: prod-app-critical
      containers:
        - name: blog
          image: ghcr.io/devsh-graphics-programming/www-blog:latest # {"$imagepolicy": "flux-system:www-blog:tag"}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
          startupProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 100
            runAsGroup: 101
          volumeMounts:
            - name: tmpfs-tmp
              mountPath: /tmp
            - name: tmpfs-config
              mountPath: /config
            - name: tmpfs-data
              mountPath: /data
      volumes:
        - name: tmpfs-tmp
          emptyDir:
            medium: Memory
        - name: tmpfs-config
          emptyDir:
            medium: Memory
        - name: tmpfs-data
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: devsh-blog
  namespace: website
spec:
  selector:
    app: devsh-blog
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devsh-blog
  namespace: website
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ${ENV_PREFIX}blog.${BASE_DOMAIN}
      secretName: devsh-blog-tls
  rules:
    - host: ${ENV_PREFIX}blog.${BASE_DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devsh-blog
                port:
                  number: 80
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devsh-website-tls
  namespace: website
spec:
  secretName: devsh-website-tls
  dnsNames:
    - ${ENV_PREFIX}${BASE_DOMAIN}
    - ${ENV_PREFIX}www.${BASE_DOMAIN}
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: devsh-blog-tls
  namespace: website
spec:
  secretName: devsh-blog-tls
  dnsNames:
    - ${ENV_PREFIX}blog.${BASE_DOMAIN}
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
