apiVersion: v1
kind: Secret
metadata:
    name: headscale-oidc
    namespace: vpn-system
type: Opaque
stringData:
    client_secret: ENC[AES256_GCM,data:Yw1FbsEhLjFSTmFCqFeb9jT3EJ81rvrjWN2t10bJwy9eSLCD3idQbwvezWZMAiDXthNt11KUiKFnzwWD9RQ7Sg==,iv:NA977rZECuNi2GvTP1qlgrqgZV29AmBaXBlq138ZB5U=,tag:VyYNisk12hx7Hc/rwcvBXg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYW1TcmpHYTFZU0NhUlR6
            V1ArQkxKZnhxQmUyQkJNbUlzMzMwbjVKZHpvCms0ckprczhVckJUcUl6aWJUcVBW
            Z3hMcEVEb0xTSXFBOHA2OERhejlPNjgKLS0tIDErTmJ6SElBa3pVVWRjblpHQ08v
            K3MvajIxSERYOGZUYW0ya1ErRENlTXcKPgGz4JyQyjdlFR+p2oGYDiGtLS32ktpH
            tZCbpBtJZJsvvpK8VVlBNU9OOM5Dz93yVmDTfCZ3xRLPdqctn3s5mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T08:30:43Z"
    mac: ENC[AES256_GCM,data:Hi4ivtaCmoSJvoIDMzwskIFs/llO2PsdnSB8lBSaVA0PrCxh2m/HkWBIGtsdGbd+ohhe1QATU8cs59C8owSRK4VR4XuuUZPRtPIR1cp/Pyo/aeM+VwhS2egPOXvjJpimChPwkvI32jD4IR33O+EkPsUMEGau/vSWBut2Or9y0jg=,iv:lODhOdIJ6rQRG4M2j8BOFC9xBdXokujCX4iF4goOLQw=,tag:1F8kgiFTmeUiM/LlvVUo5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
