apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../k8s/monitoring/monitoring-prometheus.tpl.yaml
patches:
  - target:
      group: helm.toolkit.fluxcd.io
      version: v2
      kind: HelmRelease
      name: monitoring
      namespace: monitoring
    patch: |-
      - op: replace
        path: /spec/values/prometheus/prometheusSpec/retention
        value: 5d
      - op: replace
        path: /spec/values/prometheus/prometheusSpec/retentionSize
        value: 3GB
      - op: add
        path: /spec/values/prometheus/prometheusSpec/storageSpec
        value:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 3Gi
      - op: add
        path: /spec/values/prometheus/prometheusSpec/hostAliases
        value:
          - ip: 163.172.171.121
            hostnames:
              - jenkins.devsh.eu
      - op: add
        path: /spec/values/prometheus/prometheusSpec/secrets
        value:
          - jenkins-prometheus-scrape
      - op: add
        path: /spec/values/prometheus/prometheusSpec/additionalScrapeConfigs
        value:
          - job_name: devsh-node-exporters
            scrape_interval: 60s
            static_configs:
              - targets:
                  - 51.158.67.237:9100
                labels:
                  node: devsh-k3s-prod-node-1
                  role: apps
              - targets:
                  - 51.158.103.39:9100
                labels:
                  node: prod-chat-01
                  role: chat
              - targets:
                  - 51.15.214.53:9100
                labels:
                  node: prod-rocket-01
                  role: chat
              - targets:
                  - 163.172.171.121:9100
                labels:
                  node: jenkins-prod
                  role: ci
              - targets:
                  - 51.15.227.239:9100
                labels:
                  node: prod-vpn-control-01
                  role: vpn
          - job_name: devsh-jenkins-app
            scrape_interval: 60s
            scheme: https
            metrics_path: /prometheus/
            basic_auth:
              username_file: /etc/prometheus/secrets/jenkins-prometheus-scrape/username
              password_file: /etc/prometheus/secrets/jenkins-prometheus-scrape/password
            static_configs:
              - targets:
                  - jenkins.devsh.eu
                labels:
                  node: jenkins-prod
                  role: ci
                  service: jenkins
