apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../cluster-issuer.yaml
  - ../priority-classes.tpl.yaml
  - ../flux-networkpolicies.tpl.yaml
  - ../flux-receiver.tpl.yaml
  - ../app-networkpolicies.tpl.yaml
  - ../kimai.tpl.yaml
  - ../monitoring-grafana.tpl.yaml
  - ../monitoring-oncall.tpl.yaml
  - monitoring-kustomization.yaml
  - monitoring-alerts-kustomization.yaml
  - ../dashboard.tpl.yaml
  - ../www-sites.tpl.yaml
  - ../store.tpl.yaml
  - ../grafana-dashboards
  - ../image-automation.yaml
  - ../image-digest-rollout.yaml
configMapGenerator:
  - name: store-nginx
    namespace: store
    files:
      - nginx.conf=../store/nginx.conf
    options:
      disableNameSuffixHash: false
  - name: oncall-discord-proxy
    namespace: monitoring-oncall
    files:
      - ../oncall-discord-proxy/app.py
    options:
      disableNameSuffixHash: false
