apiVersion: v1
kind: Secret
metadata:
    name: stoat-secrets
    namespace: chat
type: Opaque
stringData:
    VALID_SECRET_EXAMPLE: ENC[AES256_GCM,data:2JE919ZF/vNmz7N3Lq4=,iv:Z8pm9f59SOHCk7/N+O4RQdiOjI5RobzXJQYQYm9CvQc=,tag:68lU3JRC8SVJrFNFMppJ+g==,type:str]
    VALID_SECRET_EXAMPLE_2: ENC[AES256_GCM,data:fqSYexfTUM6JxQgxa2g9TrzFrJyJbRwWng==,iv:f34r92KOANpF9pWe2qI5K+QMHw5eWQu7SMuhAoK7/eE=,tag:/vNLp66pFXJrYRrzFIfSeA==,type:str]
    REVOLT__PUSHD__VAPID__PRIVATE_KEY: ENC[AES256_GCM,data:kCkO5jv0J5AUdn6EnAIUWZxWLbNMlNCivrZh0susJvgptccLAk/uZ4iFrPM2YZYsVujDV//XPXDCBxOEVxxOGbJTbb1tieW/lmd6FDkXwy7nxA+FyBGmjRVhh5fyKoldAlxVy7hGrNNnGKkzITTueiMeJ5oAp0stDaOO+Zxm2kFPjvtQ9+bPUtqm+ZcbcgUU27t0WT5G2JQNQ2hsT1qUYGboeCG/VHmOYVGA21djJMBdhvO3/gOsdBwwsx6y+1wWlH/TUr89txUghtqMil03CHQgwSCj1on7wbKAWuN/A7S93wGYxpPy9+EphqyvWdMa6t0b/d9Psjm3EIT7cFwqDueHUudGb0ZLpJIDtJugvCRrZsZmnwN9Ct/LXGNrdPzNmdzUVzWS9H716leCmLC9,iv:Q8aZBTSN8cXi0B45/Dv0ByPEfXvaDzhLNLsgWlGhn7s=,tag:BvP3sitb1tOuzOCuZiiiBg==,type:str]
    REVOLT__PUSHD__VAPID__PUBLIC_KEY: ENC[AES256_GCM,data:gL9sEkvoynFegHCKXig7nl2uCXBziZrPNU36gR2Nip/gOjw4W2nG09u8jpJ7hFxA/qqdefJRcD2x7jdOhDAv12ll7cV7Q5fkrdiirdRAD9dGRVNyh9NI,iv:0XTHXUXpZ+zK/sjrE9Ez3jTLFv/qb4tSq2ttEAybbJ0=,tag:xG7G5KX8h7IZzrBJOK4vYw==,type:str]
    REVOLT__FILES__ENCRYPTION_KEY: ENC[AES256_GCM,data:8Ts9tdFEVau14IYbkH6f28moLI02p36/FOBs2AsPhKInBJ5HNXpdOKPZXoU=,iv:FAf14EqycIUZA4DByGKKrBpSbOamTGSeSAUEwaU6Zcw=,tag:ydtBfmOwX7adJjlrB1N9bA==,type:str]
    REVOLT__API__LIVEKIT__NODES__WORLDWIDE__SECRET: ENC[AES256_GCM,data:6n7g3WC7+OSnSO/bQKPNMJntP4TzCazu4jnU95k8qdNm3Gz92mN0EK59pUlkexot,iv:3ndAqXKivtEGyPH9mOqArx9K+UsoFGofaSqWNx2/5Io=,tag:Pg2D3vUvLT/TOYn+piJKSQ==,type:str]
    REVOLT__API__LIVEKIT__NODES__WORLDWIDE__KEY: ENC[AES256_GCM,data:00KQ5ut3NVe51LhX,iv:fuejj8Y4EXcVw9pYLsJO/7E8Oqhf2v4//HFIS15XwSY=,tag:x6Uk3qEMWbR3aM1fhJp1zA==,type:str]
    livekit.yml: ENC[AES256_GCM,data:Fsg4AGh+CgByMpsGLtiiO9jLfMtIpeCWGOaUXXfibLX0ZJM+egS6pnqYcycn71XZPveVWpLi7vXIMYESADa3C+XpxswMoy2XsX//KCnn/Br2NIHanlVNalloxHCd2SXCDsSOK/iJ9z07wsHs49eFNL+rFjwSkdZLqDdui8lM5dxOYQ3SOVK1xL/ZObZdNuD1Tbw1gCpKbX5F22kSEyVIjZloMcSbPTVr6fnqvfkL/2QOdYG7epaZONNPTd9fAVW2WiLrL3diAPbETfN42luEOK3Xf0zwrEVQc3n/wGfgpgTHDkoGiQTZ4QnEN/F047dQDbtFnEcx5eLbDJTUxhbav4heF44RFli6swfp8FkyRgJvtZzzjISIUN0caI+fOO/CVrKLYx5UTvn1z07gbLK+Fjg=,iv:NnrWGA6hVvezLIzGgyh9EFitnwBdEahJorqoiTM2Z0o=,tag:Nqiy56dKdyTRqrUY8Ero2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRei9oVm1qa0ZwN0Y2cDlP
            QWZzU0E2TDZScUNQaFFHaFBQYzZBYklHWjJVCnhTU2VJL2FPNFluRzRVT0dXVlNU
            SUFmcFlqaGU5ZEtoTk0ySGVZZHFVb3cKLS0tIHBWRXR3eDdPWGRSYldyZ1N4d1VX
            KzhWeXpkZ2pNMFBzWForSmE2Q3U3MTQKjBZMUV/8Q3Yqrr3TZ9fRnMvcnvsNRPdm
            tDPp56YJenm794iHN8K4/QKZdfdTUy6kdLX+lKg5fc4Avx6H9PFpjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T12:00:07Z"
    mac: ENC[AES256_GCM,data:++yqv5BXIp5BPqmsbVaF6mb2wUOAhtuBXI5WWuDHgrNIkh++CKJIkxpimcE1iXycHiXHstvzPELjFgI3ONT8TEEG8RNOf+0ogbWIU4y99YtIGnSUsxWBhI+FWT5Oq7ZhhDXBMF0eL+fQnMb/40IPHh1921tye+uOceP4wLyN9UQ=,iv:i+LfQHkjV0mnR74LomO+KWfUgaZJ9p0mcp9emSeOBBA=,tag:hqjWMakAuBv7ElGVXT1Ibg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
