apiVersion: v1
kind: Secret
metadata:
    name: stoat-secrets
    namespace: chat
type: Opaque
stringData:
    VALID_SECRET_EXAMPLE: ENC[AES256_GCM,data:KI98/5Fb5vg495sDYd9i2g==,iv:R/AIj9pOdI2EAsmlgM781E1ZJyrC18YqmpvU6U2TLNQ=,tag:8Do4C40sKfzoNoN+Uey2mQ==,type:str]
    VALID_SECRET_EXAMPLE_2: ENC[AES256_GCM,data:ZwKvvBIqyD6JQHmKq7SD/WX+6HP0mcWKlr1j,iv:+aJcrYUghFHBGKvqR55oCSh+/6X3l/Yq9ge+J4eG6dE=,tag:hD1q3PqnE0ES8XHxDmJgFg==,type:str]
    REVOLT__PUSHD__VAPID__PRIVATE_KEY: ENC[AES256_GCM,data:8oIMMxqgRnSsHMvzZZGEnswXj/zcAK6mal9NBkv1XgSjmDb7i/Irrl839qMRGxPvzlkM7FSTA31a4ZGt48G2OYstbQ4odM/TbHk7yHZrasRl3tfYeyAbnQrJ7BA+28/nVK1DnhAjeFvSTtuyKVz7qrDLfKiKKEwcewDlMUEBepIwkkxZ+Zt9bFzqR7OhR7NhlmqTOeloYrvFjh+Ao03QzzqrrktHauc3dqytvLk377NWLBNevcJG7PbcFHhmVCJRYU6aCvozteHiO6BO3SEsbGeArWbpQtqXWfpVRNVNIVsvltOn0Ntju60gAnn046pH/NJZa+dG8A6V6328WAcltxFadnCms6FQSeMg/ELtF++IHl/EiMN3DGs1v75AsM+38b5w2y1C4JuutIuKs0SnKVk=,iv:m5eu4f8ctUX0EZiXzLRmK7H6/P4kFKA1MlxMZKWLT8I=,tag:OApqYUIPuIUy9zOj2h73eA==,type:str]
    REVOLT__PUSHD__VAPID__PUBLIC_KEY: ENC[AES256_GCM,data:xB+OJYK8wEtiXHpEqiUMiq/ye2RPDjciNK5yVAckRAcluQL8523pVKswPyVOQIlIiIjOgrDC0p5AxeXXHhl6xdfRs0BooRq7hdRr7sf2VXQP3FjhxwGlesA=,iv:SypEj8Rlztu57vy2QmIpPiabfX7LtUy7e8VbIpH+F10=,tag:frqRFbytnrrUEwUkuo0UnQ==,type:str]
    REVOLT__FILES__ENCRYPTION_KEY: ENC[AES256_GCM,data:QJ2GesEsMvr7EPVmNcXn9qHFEwMwzGdrHUg482fRqQzvgymZrgbgcWaRFkxWkA==,iv:3oE9Hginj3uvh4WRNWb6ReOW1IUrTXSEkRh9GT8CFi8=,tag:Iq/VlGG8EWbcnGYWzISw8Q==,type:str]
    REVOLT__API__LIVEKIT__NODES__WORLDWIDE__SECRET: ENC[AES256_GCM,data:26deTCaBxu2+wP5n8jksjqCtAycFcA/cCLdQ2mTtQsHiH1sHrevT9xL3kGUYWegAeQo=,iv:vqL1CJokswQZQfPH/PPC7faXcBt/swAXBindVDkbjMU=,tag:syTOo0C0YqaC6R1UNnVVRQ==,type:str]
    REVOLT__API__LIVEKIT__NODES__WORLDWIDE__KEY: ENC[AES256_GCM,data:VXyeY38xQYTs2RCrVF0=,iv:0qCUXe2h1vuuion8DcuWURDmYNWSkCWwg6Lz6VKrgKw=,tag:a98BjnMCr9+puqwfxnzVmA==,type:str]
    livekit.yml: ENC[AES256_GCM,data:HFo6TeioQoWBQOudpAeC10/6MhM4US03qc6Pou05wR2EC/bmw+oPF6hr7ivBKOVg0K3qvqLvDCMHaEWSBnt/Ae0nHles3w/R0NOJzYkJVOkTggl5EjYbK5VyJLOG4cUKO9Pi8MVvYG4mJxGs4H6atleyZyiTDhn5FaZRBkcjaxsj9C1inFXiCkx825kuHBXVH+WHnittyIVodLdYAW1RWsoJ90nBy418XWbLeCu+aY5XBtHsEw5ui2s9D8ftbrJIR/razjMbdo+TOfBQ+qAdTI/kWDuNCPsliQjFagcBkOmD0ikeGvljZZMLtqiGUyKH1KOO9Fu2r5LbzakOxfTUBgiWTQ++37QSuumECJtlEuUphdUm1febyLn63GNTjhfCYExPF2nR6it+5jqc/yKwmQw=,iv:9r/Wmbxm/l6cuecEvOPGtJNlRMwY/dLckyHjTdQK0MY=,tag:SfEkDXRkKO8zJZcpwQBkNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeDNmVkRZa04vMmFWOWJi
            YzVzM1FFd25IRkxBemFVb1BGWXpSWWh0QXpjCnVpc0NNZGhESGNvRi9SdlFGZjcr
            KzFzby9Eb3dGVzREQy9uNEJoQU02SUkKLS0tIFVQajFYazNPeXd3bFpBWHovaG53
            QTBuNForVXhERFpIaGpvbFdQeVVodDQKdYphoi05gGiZ82E78k/Uif9MCVtXRFfL
            SmZr2hXKM+8c05Tqt/WaSpKiGk2I/R10hzv6GFym3NCChQEOD5zu8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-22T11:13:06Z"
    mac: ENC[AES256_GCM,data:Xu3KYbhm0TxhifF6YSRPhYhWaWFVtPbGjPHKwaqoqb02jbT9TUJpWnCmYWwitKojuBNgNcsfqLudghcuLrEAihxX40lBpCupheLfiQy2etG3pd4gS0i0Qx7MCqEz+0MkxMhqkt1luHkZi4vKUx5xg+jjyPWSBxRZoYEVIJc//mE=,iv:IPjM3wjQj7SsCBIx3QtnAQbWpVU7hu/XQQwHK/k6ZLE=,tag:O1yr5koO5Ne8mPoT6YHScw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
