apiVersion: v1
kind: Secret
metadata:
    name: tailscale-auth
    namespace: chat
type: Opaque
stringData:
    TS_AUTHKEY: ENC[AES256_GCM,data:hpOUNoDMvFwbPuexKx4moE1aw/6UPKVtt9l+yuh36xZkqiHLPMVmxsZRnEiiX5sARjdswGMTWGlFqEZwVNrkKL+93ZU7sF0GWpot9F36kKrd2XkPRZnvLQ==,iv:gwKdXJc70ktH+oIE1kL/zFTryxQbL1f7Y14fqVkxEd4=,tag:xBlLNqTR7PBuT0d4HvScJQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uzjp5mkpt8skuc5r8lnlhhd0jdfmplf0s6atg0sn5x37j8v2p9qqswgshr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZHdVaUtHTWcxeWhSMHhO
            SzZscGs0RXRES2I4YkUxeFVrVVRNdjdPWWxRClkzOWEwSjZHNlVtVnpqRkhjcGZP
            Z09RbFlqdUFvYkRwNHczVzRRMFdrdUUKLS0tIGMzck9kN0VpUExYcTVIK0ZkR2JO
            bm92elhRUGJUTFc1T3VNdkpJMC9hdUUKyhXrlkH5XevILDsMUpyl90LmFf9Xa5Ug
            jqYRQ13uNmYQIsO1baIzXQkYSXynDqrbM18ZhgbHA0g203np9EJ8+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-14T08:56:41Z"
    mac: ENC[AES256_GCM,data:eRHSwK27UhUufMKA4mCYQXgcaCbcTBvKSP9aBOJAhS8/kBROL3/0pCFyc6wduCLH8EHf1MmLqeAlbn8D4AyQXeclkr8eGDuGHHkvwEF7AUSL08c14G3yFZxvUocU3fhx6lroPaCcgStupX8yb9eQ/V3u7yKQXxY+jmshwecIMYM=,iv:H0YIljaPbyhQUJs2TffQSGDrRhPVGHKZWgc6iWD3UVQ=,tag:akWn4e+X11NBpfQQPaTf/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
