apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-vars
  namespace: flux-system
  labels:
    reconcile.fluxcd.io/watch: "Enabled"
data:
  BASE_DOMAIN: ${BASE_DOMAIN}
  ENV_PREFIX: ${ENV_PREFIX}
  ACME_EMAIL: ${ACME_EMAIL}
  NODE_NAME: ${NODE_NAME}
